import {
  faBook,
  faBuildingColumns,
  faCar,
  faCartShopping,
  faElevator,
  faHamburger,
  faIceCream,
  faMugSaucer,
  faSquareParking,
  faTicket,
  faUtensils,
  faWheelchair,
  faWifi,
} from "@fortawesome/free-solid-svg-icons";
import {
  faClock,
  faCreditCard,
  faHeart,
} from "@fortawesome/free-regular-svg-icons";

export const heart = faHeart;
export const clock = faClock;

export const statusList = [
  { status: "available", color: "#bcc7d6" },
  { status: "unavailable", color: "#21222a" },
  { status: "chosen", color: "#ff3543" },
  { status: "soldOut", color: "#555f6d" },
];

export const SalonSeat = [
  {
    salonName: "گراند سینما(1)",
    chairs: [
      { column: "1", row: "Q", price: "60,000 تومان", status: "available" },
      { column: "2", row: "Q", price: "60,000 تومان", status: "available" },
      { column: "3", row: "Q", price: "60,000 تومان", status: "available" },
      { column: "4", row: "Q", price: "60,000 تومان", status: "available" },
      { column: "5", row: "Q", price: "60,000 تومان", status: "available" },
      { column: "6", row: "Q", price: "60,000 تومان", status: "available" },
      { column: "7", row: "Q", price: "60,000 تومان", status: "available" },
      { column: "8", row: "Q", price: "60,000 تومان", status: "available" },
      { column: "9", row: "Q", price: "60,000 تومان", status: "available" },
      { column: "10", row: "Q", price: "60,000 تومان", status: "available" },
      { column: "11", row: "Q", price: "60,000 تومان", status: "available" },
      { column: "12", row: "Q", price: "60,000 تومان", status: "available" },
      { column: "13", row: "Q", price: "60,000 تومان", status: "available" },
      { column: "14", row: "Q", price: "60,000 تومان", status: "available" },
      { column: "15", row: "Q", price: "60,000 تومان", status: "available" },
      { column: "16", row: "Q", price: "60,000 تومان", status: "available" },
      { column: "17", row: "Q", price: "60,000 تومان", status: "available" },
      { column: "18", row: "Q", price: "60,000 تومان", status: "available" },
      { column: "19", row: "Q", price: "60,000 تومان", status: "available" },
      { column: "20", row: "Q", price: "60,000 تومان", status: "available" },
      { column: "21", row: "Q", price: "60,000 تومان", status: "available" },
      { column: "22", row: "Q", price: "60,000 تومان", status: "available" },
      { column: "23", row: "Q", price: "60,000 تومان", status: "available" },
      { column: "24", row: "Q", price: "60,000 تومان", status: "available" },
      { column: "25", row: "Q", price: "60,000 تومان", status: "available" },
      { column: "1", row: "P", price: "60,000 تومان", status: "available" },
      { column: "2", row: "P", price: "60,000 تومان", status: "available" },
      { column: "3", row: "P", price: "60,000 تومان", status: "available" },
      { column: "4", row: "P", price: "60,000 تومان", status: "available" },
      { column: "5", row: "P", price: "60,000 تومان", status: "available" },
      { column: "6", row: "P", price: "60,000 تومان", status: "available" },
      { column: "7", row: "P", price: "60,000 تومان", status: "available" },
      { column: "8", row: "P", price: "60,000 تومان", status: "available" },
      { column: "9", row: "P", price: "60,000 تومان", status: "available" },
      { column: "10", row: "P", price: "60,000 تومان", status: "available" },
      { column: "11", row: "P", price: "60,000 تومان", status: "available" },
      { column: "12", row: "P", price: "60,000 تومان", status: "available" },
      { column: "13", row: "P", price: "60,000 تومان", status: "available" },
      { column: "14", row: "P", price: "60,000 تومان", status: "available" },
      { column: "15", row: "P", price: "60,000 تومان", status: "available" },
      { column: "16", row: "P", price: "60,000 تومان", status: "available" },
      { column: "17", row: "P", price: "60,000 تومان", status: "available" },
      { column: "18", row: "P", price: "60,000 تومان", status: "available" },
      { column: "19", row: "P", price: "60,000 تومان", status: "available" },
      { column: "20", row: "P", price: "60,000 تومان", status: "available" },
      { column: "21", row: "P", price: "60,000 تومان", status: "available" },
      { column: "22", row: "P", price: "60,000 تومان", status: "available" },
      { column: "23", row: "P", price: "60,000 تومان", status: "available" },
      { column: "24", row: "P", price: "60,000 تومان", status: "available" },
      { column: "25", row: "P", price: "60,000 تومان", status: "available" },
      { column: "1", row: "O", price: "60,000 تومان", status: "available" },
      { column: "2", row: "O", price: "60,000 تومان", status: "available" },
      { column: "3", row: "O", price: "60,000 تومان", status: "available" },
      { column: "4", row: "O", price: "60,000 تومان", status: "available" },
      { column: "5", row: "O", price: "60,000 تومان", status: "available" },
      { column: "6", row: "O", price: "60,000 تومان", status: "available" },
      { column: "7", row: "O", price: "60,000 تومان", status: "available" },
      { column: "8", row: "O", price: "60,000 تومان", status: "available" },
      { column: "9", row: "O", price: "60,000 تومان", status: "available" },
      { column: "10", row: "O", price: "60,000 تومان", status: "available" },
      { column: "11", row: "O", price: "60,000 تومان", status: "available" },
      { column: "12", row: "O", price: "60,000 تومان", status: "available" },
      { column: "13", row: "O", price: "60,000 تومان", status: "available" },
      { column: "14", row: "O", price: "60,000 تومان", status: "available" },
      { column: "15", row: "O", price: "60,000 تومان", status: "available" },
      { column: "16", row: "O", price: "60,000 تومان", status: "available" },
      { column: "17", row: "O", price: "60,000 تومان", status: "available" },
      { column: "18", row: "O", price: "60,000 تومان", status: "available" },
      { column: "19", row: "O", price: "60,000 تومان", status: "available" },
      { column: "20", row: "O", price: "60,000 تومان", status: "available" },
      { column: "21", row: "O", price: "60,000 تومان", status: "available" },
      { column: "22", row: "O", price: "60,000 تومان", status: "available" },
      { column: "23", row: "O", price: "60,000 تومان", status: "available" },
      { column: "24", row: "O", price: "60,000 تومان", status: "available" },
      { column: "25", row: "O", price: "60,000 تومان", status: "available" },
      { column: "1", row: "N", price: "60,000 تومان", status: "available" },
      { column: "2", row: "N", price: "60,000 تومان", status: "available" },
      { column: "3", row: "N", price: "60,000 تومان", status: "available" },
      { column: "4", row: "N", price: "60,000 تومان", status: "available" },
      { column: "5", row: "N", price: "60,000 تومان", status: "available" },
      { column: "6", row: "N", price: "60,000 تومان", status: "available" },
      { column: "7", row: "N", price: "60,000 تومان", status: "available" },
      { column: "8", row: "N", price: "60,000 تومان", status: "available" },
      { column: "9", row: "N", price: "60,000 تومان", status: "available" },
      { column: "10", row: "N", price: "60,000 تومان", status: "available" },
      { column: "11", row: "N", price: "60,000 تومان", status: "available" },
      { column: "12", row: "N", price: "60,000 تومان", status: "available" },
      { column: "13", row: "N", price: "60,000 تومان", status: "available" },
      { column: "14", row: "N", price: "60,000 تومان", status: "available" },
      { column: "15", row: "N", price: "60,000 تومان", status: "available" },
      { column: "16", row: "N", price: "60,000 تومان", status: "available" },
      { column: "17", row: "N", price: "60,000 تومان", status: "available" },
      { column: "18", row: "N", price: "60,000 تومان", status: "available" },
      { column: "19", row: "N", price: "60,000 تومان", status: "available" },
      { column: "20", row: "N", price: "60,000 تومان", status: "available" },
      { column: "21", row: "N", price: "60,000 تومان", status: "available" },
      { column: "22", row: "N", price: "60,000 تومان", status: "available" },
      { column: "23", row: "N", price: "60,000 تومان", status: "available" },
      { column: "24", row: "N", price: "60,000 تومان", status: "available" },
      { column: "25", row: "N", price: "60,000 تومان", status: "available" },
      { column: "1", row: "M", price: "60,000 تومان", status: "available" },
      { column: "2", row: "M", price: "60,000 تومان", status: "available" },
      { column: "3", row: "M", price: "60,000 تومان", status: "available" },
      { column: "4", row: "M", price: "60,000 تومان", status: "available" },
      { column: "5", row: "M", price: "60,000 تومان", status: "available" },
      { column: "6", row: "M", price: "60,000 تومان", status: "available" },
      { column: "7", row: "M", price: "60,000 تومان", status: "available" },
      { column: "8", row: "M", price: "60,000 تومان", status: "available" },
      { column: "9", row: "M", price: "60,000 تومان", status: "available" },
      { column: "10", row: "M", price: "60,000 تومان", status: "available" },
      { column: "11", row: "M", price: "60,000 تومان", status: "available" },
      { column: "12", row: "M", price: "60,000 تومان", status: "available" },
      { column: "13", row: "M", price: "60,000 تومان", status: "available" },
      { column: "14", row: "M", price: "60,000 تومان", status: "available" },
      { column: "15", row: "M", price: "60,000 تومان", status: "available" },
      { column: "16", row: "M", price: "60,000 تومان", status: "available" },
      { column: "17", row: "M", price: "60,000 تومان", status: "available" },
      { column: "18", row: "M", price: "60,000 تومان", status: "available" },
      { column: "19", row: "M", price: "60,000 تومان", status: "available" },
      { column: "20", row: "M", price: "60,000 تومان", status: "available" },
      { column: "21", row: "M", price: "60,000 تومان", status: "available" },
      { column: "22", row: "M", price: "60,000 تومان", status: "available" },
      { column: "23", row: "M", price: "60,000 تومان", status: "available" },
      { column: "24", row: "M", price: "60,000 تومان", status: "available" },
      { column: "25", row: "M", price: "60,000 تومان", status: "available" },
      { column: "1", row: "L", price: "60,000 تومان", status: "available" },
      { column: "2", row: "L", price: "60,000 تومان", status: "available" },
      { column: "3", row: "L", price: "60,000 تومان", status: "available" },
      { column: "4", row: "L", price: "60,000 تومان", status: "available" },
      { column: "5", row: "L", price: "60,000 تومان", status: "available" },
      { column: "6", row: "L", price: "60,000 تومان", status: "available" },
      { column: "7", row: "L", price: "60,000 تومان", status: "available" },
      { column: "8", row: "L", price: "60,000 تومان", status: "available" },
      { column: "9", row: "L", price: "60,000 تومان", status: "available" },
      { column: "10", row: "L", price: "60,000 تومان", status: "available" },
      { column: "11", row: "L", price: "60,000 تومان", status: "available" },
      { column: "12", row: "L", price: "60,000 تومان", status: "available" },
      { column: "13", row: "L", price: "60,000 تومان", status: "available" },
      { column: "14", row: "L", price: "60,000 تومان", status: "available" },
      { column: "15", row: "L", price: "60,000 تومان", status: "available" },
      { column: "16", row: "L", price: "60,000 تومان", status: "available" },
      { column: "17", row: "L", price: "60,000 تومان", status: "available" },
      { column: "18", row: "L", price: "60,000 تومان", status: "available" },
      { column: "19", row: "L", price: "60,000 تومان", status: "available" },
      { column: "20", row: "L", price: "60,000 تومان", status: "available" },
      { column: "21", row: "L", price: "60,000 تومان", status: "available" },
      { column: "22", row: "L", price: "60,000 تومان", status: "available" },
      { column: "23", row: "L", price: "60,000 تومان", status: "available" },
      { column: "24", row: "L", price: "60,000 تومان", status: "available" },
      { column: "25", row: "L", price: "60,000 تومان", status: "available" },
      { column: "1", row: "K", price: "60,000 تومان", status: "available" },
      { column: "2", row: "K", price: "60,000 تومان", status: "available" },
      { column: "3", row: "K", price: "60,000 تومان", status: "available" },
      { column: "4", row: "K", price: "60,000 تومان", status: "available" },
      { column: "5", row: "K", price: "60,000 تومان", status: "available" },
      { column: "6", row: "K", price: "60,000 تومان", status: "available" },
      { column: "7", row: "K", price: "60,000 تومان", status: "available" },
      { column: "8", row: "K", price: "60,000 تومان", status: "available" },
      { column: "9", row: "K", price: "60,000 تومان", status: "available" },
      { column: "10", row: "K", price: "60,000 تومان", status: "available" },
      { column: "11", row: "K", price: "60,000 تومان", status: "available" },
      { column: "12", row: "K", price: "60,000 تومان", status: "available" },
      { column: "13", row: "K", price: "60,000 تومان", status: "available" },
      { column: "14", row: "K", price: "60,000 تومان", status: "available" },
      { column: "15", row: "K", price: "60,000 تومان", status: "available" },
      { column: "16", row: "K", price: "60,000 تومان", status: "available" },
      { column: "17", row: "K", price: "60,000 تومان", status: "available" },
      { column: "18", row: "K", price: "60,000 تومان", status: "available" },
      { column: "19", row: "K", price: "60,000 تومان", status: "available" },
      { column: "20", row: "K", price: "60,000 تومان", status: "available" },
      { column: "21", row: "K", price: "60,000 تومان", status: "available" },
      { column: "22", row: "K", price: "60,000 تومان", status: "available" },
      { column: "23", row: "K", price: "60,000 تومان", status: "available" },
      { column: "24", row: "K", price: "60,000 تومان", status: "available" },
      { column: "25", row: "K", price: "60,000 تومان", status: "available" },
      { column: "1", row: "J", price: "60,000 تومان", status: "available" },
      { column: "2", row: "J", price: "60,000 تومان", status: "available" },
      { column: "3", row: "J", price: "60,000 تومان", status: "available" },
      { column: "4", row: "J", price: "60,000 تومان", status: "available" },
      { column: "5", row: "J", price: "60,000 تومان", status: "available" },
      { column: "6", row: "J", price: "60,000 تومان", status: "available" },
      { column: "7", row: "J", price: "60,000 تومان", status: "available" },
      { column: "8", row: "J", price: "60,000 تومان", status: "available" },
      { column: "9", row: "J", price: "60,000 تومان", status: "available" },
      { column: "10", row: "J", price: "60,000 تومان", status: "available" },
      { column: "11", row: "J", price: "60,000 تومان", status: "available" },
      { column: "12", row: "J", price: "60,000 تومان", status: "available" },
      { column: "13", row: "J", price: "60,000 تومان", status: "available" },
      { column: "14", row: "J", price: "60,000 تومان", status: "available" },
      { column: "15", row: "J", price: "60,000 تومان", status: "available" },
      { column: "16", row: "J", price: "60,000 تومان", status: "available" },
      { column: "17", row: "J", price: "60,000 تومان", status: "available" },
      { column: "18", row: "J", price: "60,000 تومان", status: "available" },
      { column: "19", row: "J", price: "60,000 تومان", status: "available" },
      { column: "20", row: "J", price: "60,000 تومان", status: "available" },
      { column: "21", row: "J", price: "60,000 تومان", status: "available" },
      { column: "22", row: "J", price: "60,000 تومان", status: "available" },
      { column: "23", row: "J", price: "60,000 تومان", status: "available" },
      { column: "24", row: "J", price: "60,000 تومان", status: "available" },
      { column: "25", row: "J", price: "60,000 تومان", status: "available" },
      { column: "1", row: "I", price: "60,000 تومان", status: "available" },
      { column: "2", row: "I", price: "60,000 تومان", status: "available" },
      { column: "3", row: "I", price: "60,000 تومان", status: "available" },
      { column: "4", row: "I", price: "60,000 تومان", status: "available" },
      { column: "5", row: "I", price: "60,000 تومان", status: "available" },
      { column: "6", row: "I", price: "60,000 تومان", status: "available" },
      { column: "7", row: "I", price: "60,000 تومان", status: "available" },
      { column: "8", row: "I", price: "60,000 تومان", status: "available" },
      { column: "9", row: "I", price: "60,000 تومان", status: "available" },
      { column: "10", row: "I", price: "60,000 تومان", status: "available" },
      { column: "11", row: "I", price: "60,000 تومان", status: "available" },
      { column: "12", row: "I", price: "60,000 تومان", status: "available" },
      { column: "13", row: "I", price: "60,000 تومان", status: "available" },
      { column: "14", row: "I", price: "60,000 تومان", status: "available" },
      { column: "15", row: "I", price: "60,000 تومان", status: "available" },
      { column: "16", row: "I", price: "60,000 تومان", status: "available" },
      { column: "17", row: "I", price: "60,000 تومان", status: "available" },
      { column: "18", row: "I", price: "60,000 تومان", status: "available" },
      { column: "19", row: "I", price: "60,000 تومان", status: "available" },
      { column: "20", row: "I", price: "60,000 تومان", status: "available" },
      { column: "21", row: "I", price: "60,000 تومان", status: "available" },
      { column: "22", row: "I", price: "60,000 تومان", status: "available" },
      { column: "23", row: "I", price: "60,000 تومان", status: "available" },
      { column: "24", row: "I", price: "60,000 تومان", status: "available" },
      { column: "25", row: "I", price: "60,000 تومان", status: "available" },
      { column: "1", row: "H", price: "60,000 تومان", status: "available" },
      { column: "2", row: "H", price: "60,000 تومان", status: "available" },
      { column: "3", row: "H", price: "60,000 تومان", status: "available" },
      { column: "4", row: "H", price: "60,000 تومان", status: "available" },
      { column: "5", row: "H", price: "60,000 تومان", status: "available" },
      { column: "6", row: "H", price: "60,000 تومان", status: "available" },
      { column: "7", row: "H", price: "60,000 تومان", status: "available" },
      { column: "8", row: "H", price: "60,000 تومان", status: "available" },
      { column: "9", row: "H", price: "60,000 تومان", status: "available" },
      { column: "10", row: "H", price: "60,000 تومان", status: "available" },
      { column: "11", row: "H", price: "60,000 تومان", status: "available" },
      { column: "12", row: "H", price: "60,000 تومان", status: "available" },
      { column: "13", row: "H", price: "60,000 تومان", status: "available" },
      { column: "14", row: "H", price: "60,000 تومان", status: "available" },
      { column: "15", row: "H", price: "60,000 تومان", status: "available" },
      { column: "16", row: "H", price: "60,000 تومان", status: "available" },
      { column: "17", row: "H", price: "60,000 تومان", status: "available" },
      { column: "18", row: "H", price: "60,000 تومان", status: "available" },
      { column: "19", row: "H", price: "60,000 تومان", status: "available" },
      { column: "20", row: "H", price: "60,000 تومان", status: "available" },
      { column: "21", row: "H", price: "60,000 تومان", status: "available" },
      { column: "22", row: "H", price: "60,000 تومان", status: "available" },
      { column: "23", row: "H", price: "60,000 تومان", status: "available" },
      { column: "24", row: "H", price: "60,000 تومان", status: "available" },
      { column: "25", row: "H", price: "60,000 تومان", status: "available" },
      { column: "1", row: "G", price: "60,000 تومان", status: "available" },
      { column: "2", row: "G", price: "60,000 تومان", status: "available" },
      { column: "3", row: "G", price: "60,000 تومان", status: "available" },
      { column: "4", row: "G", price: "60,000 تومان", status: "available" },
      { column: "5", row: "G", price: "60,000 تومان", status: "available" },
      { column: "6", row: "G", price: "60,000 تومان", status: "available" },
      { column: "7", row: "G", price: "60,000 تومان", status: "available" },
      { column: "8", row: "G", price: "60,000 تومان", status: "available" },
      { column: "9", row: "G", price: "60,000 تومان", status: "available" },
      { column: "10", row: "G", price: "60,000 تومان", status: "available" },
      { column: "11", row: "G", price: "60,000 تومان", status: "available" },
      { column: "12", row: "G", price: "60,000 تومان", status: "available" },
      { column: "13", row: "G", price: "60,000 تومان", status: "available" },
      { column: "14", row: "G", price: "60,000 تومان", status: "available" },
      { column: "15", row: "G", price: "60,000 تومان", status: "available" },
      { column: "16", row: "G", price: "60,000 تومان", status: "available" },
      { column: "17", row: "G", price: "60,000 تومان", status: "available" },
      { column: "18", row: "G", price: "60,000 تومان", status: "available" },
      { column: "19", row: "G", price: "60,000 تومان", status: "available" },
      { column: "20", row: "G", price: "60,000 تومان", status: "available" },
      { column: "21", row: "G", price: "60,000 تومان", status: "available" },
      { column: "22", row: "G", price: "60,000 تومان", status: "available" },
      { column: "23", row: "G", price: "60,000 تومان", status: "available" },
      { column: "24", row: "G", price: "60,000 تومان", status: "available" },
      { column: "25", row: "G", price: "60,000 تومان", status: "available" },
      { column: "1", row: "F", price: "60,000 تومان", status: "available" },
      { column: "2", row: "F", price: "60,000 تومان", status: "available" },
      { column: "3", row: "F", price: "60,000 تومان", status: "available" },
      { column: "4", row: "F", price: "60,000 تومان", status: "available" },
      { column: "5", row: "F", price: "60,000 تومان", status: "available" },
      { column: "6", row: "F", price: "60,000 تومان", status: "available" },
      { column: "7", row: "F", price: "60,000 تومان", status: "available" },
      { column: "8", row: "F", price: "60,000 تومان", status: "available" },
      { column: "9", row: "F", price: "60,000 تومان", status: "available" },
      { column: "10", row: "F", price: "60,000 تومان", status: "available" },
      { column: "11", row: "F", price: "60,000 تومان", status: "available" },
      { column: "12", row: "F", price: "60,000 تومان", status: "available" },
      { column: "13", row: "F", price: "60,000 تومان", status: "available" },
      { column: "14", row: "F", price: "60,000 تومان", status: "available" },
      { column: "15", row: "F", price: "60,000 تومان", status: "available" },
      { column: "16", row: "F", price: "60,000 تومان", status: "available" },
      { column: "17", row: "F", price: "60,000 تومان", status: "available" },
      { column: "18", row: "F", price: "60,000 تومان", status: "available" },
      { column: "19", row: "F", price: "60,000 تومان", status: "available" },
      { column: "20", row: "F", price: "60,000 تومان", status: "available" },
      { column: "21", row: "F", price: "60,000 تومان", status: "available" },
      { column: "22", row: "F", price: "60,000 تومان", status: "available" },
      { column: "23", row: "F", price: "60,000 تومان", status: "available" },
      { column: "24", row: "F", price: "60,000 تومان", status: "available" },
      { column: "25", row: "F", price: "60,000 تومان", status: "available" },
      { column: "0", row: "E", price: "60,000 تومان", status: "unavailable" },
      { column: "0", row: "E", price: "60,000 تومان", status: "unavailable" },
      { column: "0", row: "E", price: "60,000 تومان", status: "unavailable" },
      { column: "4", row: "E", price: "60,000 تومان", status: "available" },
      { column: "5", row: "E", price: "60,000 تومان", status: "available" },
      { column: "6", row: "E", price: "60,000 تومان", status: "available" },
      { column: "7", row: "E", price: "60,000 تومان", status: "available" },
      { column: "8", row: "E", price: "60,000 تومان", status: "available" },
      { column: "9", row: "E", price: "60,000 تومان", status: "available" },
      { column: "10", row: "E", price: "60,000 تومان", status: "available" },
      { column: "11", row: "E", price: "60,000 تومان", status: "available" },
      { column: "12", row: "E", price: "60,000 تومان", status: "available" },
      { column: "13", row: "E", price: "60,000 تومان", status: "available" },
      { column: "14", row: "E", price: "60,000 تومان", status: "available" },
      { column: "15", row: "E", price: "60,000 تومان", status: "available" },
      { column: "16", row: "E", price: "60,000 تومان", status: "available" },
      { column: "17", row: "E", price: "60,000 تومان", status: "available" },
      { column: "18", row: "E", price: "60,000 تومان", status: "available" },
      { column: "19", row: "E", price: "60,000 تومان", status: "available" },
      { column: "20", row: "E", price: "60,000 تومان", status: "available" },
      { column: "21", row: "E", price: "60,000 تومان", status: "available" },
      { column: "0", row: "E", price: "60,000 تومان", status: "unavailable" },
      { column: "0", row: "E", price: "60,000 تومان", status: "unavailable" },
      { column: "0", row: "E", price: "60,000 تومان", status: "unavailable" },
      { column: "0", row: "E", price: "60,000 تومان", status: "unavailable" },
      { column: "0", row: "D", price: "60,000 تومان", status: "unavailable" },
      { column: "0", row: "D", price: "60,000 تومان", status: "unavailable" },
      { column: "0", row: "D", price: "60,000 تومان", status: "unavailable" },
      { column: "0", row: "D", price: "60,000 تومان", status: "unavailable" },
      { column: "0", row: "D", price: "60,000 تومان", status: "unavailable" },
      { column: "0", row: "D", price: "60,000 تومان", status: "unavailable" },
      { column: "7", row: "D", price: "60,000 تومان", status: "available" },
      { column: "8", row: "D", price: "60,000 تومان", status: "available" },
      { column: "9", row: "D", price: "60,000 تومان", status: "available" },
      { column: "10", row: "D", price: "60,000 تومان", status: "available" },
      { column: "11", row: "D", price: "60,000 تومان", status: "available" },
      { column: "12", row: "D", price: "60,000 تومان", status: "available" },
      { column: "13", row: "D", price: "60,000 تومان", status: "available" },
      { column: "14", row: "D", price: "60,000 تومان", status: "available" },
      { column: "15", row: "D", price: "60,000 تومان", status: "available" },
      { column: "16", row: "D", price: "60,000 تومان", status: "available" },
      { column: "17", row: "D", price: "60,000 تومان", status: "available" },
      { column: "18", row: "D", price: "60,000 تومان", status: "available" },
      { column: "19", row: "D", price: "60,000 تومان", status: "available" },
      { column: "20", row: "D", price: "60,000 تومان", status: "available" },
      { column: "21", row: "D", price: "60,000 تومان", status: "available" },
      { column: "22", row: "D", price: "60,000 تومان", status: "available" },
      { column: "23", row: "D", price: "60,000 تومان", status: "available" },
      { column: "24", row: "D", price: "60,000 تومان", status: "available" },
      { column: "0", row: "D", price: "60,000 تومان", status: "unavailable" },
      { column: "0", row: "C", price: "60,000 تومان", status: "unavailable" },
      { column: "0", row: "C", price: "60,000 تومان", status: "unavailable" },
      { column: "0", row: "C", price: "60,000 تومان", status: "unavailable" },
      { column: "0", row: "C", price: "60,000 تومان", status: "unavailable" },
      { column: "0", row: "C", price: "60,000 تومان", status: "unavailable" },
      { column: "0", row: "C", price: "60,000 تومان", status: "unavailable" },
      { column: "7", row: "C", price: "60,000 تومان", status: "available" },
      { column: "8", row: "C", price: "60,000 تومان", status: "available" },
      { column: "9", row: "C", price: "60,000 تومان", status: "available" },
      { column: "10", row: "C", price: "60,000 تومان", status: "available" },
      { column: "11", row: "C", price: "60,000 تومان", status: "available" },
      { column: "12", row: "C", price: "60,000 تومان", status: "available" },
      { column: "13", row: "C", price: "60,000 تومان", status: "available" },
      { column: "14", row: "C", price: "60,000 تومان", status: "available" },
      { column: "15", row: "C", price: "60,000 تومان", status: "available" },
      { column: "16", row: "C", price: "60,000 تومان", status: "available" },
      { column: "17", row: "C", price: "60,000 تومان", status: "available" },
      { column: "18", row: "C", price: "60,000 تومان", status: "available" },
      { column: "19", row: "C", price: "60,000 تومان", status: "available" },
      { column: "20", row: "C", price: "60,000 تومان", status: "available" },
      { column: "21", row: "C", price: "60,000 تومان", status: "available" },
      { column: "22", row: "C", price: "60,000 تومان", status: "available" },
      { column: "23", row: "C", price: "60,000 تومان", status: "available" },
      { column: "24", row: "C", price: "60,000 تومان", status: "available" },
      { column: "0", row: "C", price: "60,000 تومان", status: "unavailable" },
      { column: "0", row: "B", price: "60,000 تومان", status: "unavailable" },
      { column: "2", row: "B", price: "60,000 تومان", status: "available" },
      { column: "3", row: "B", price: "60,000 تومان", status: "available" },
      { column: "4", row: "B", price: "60,000 تومان", status: "available" },
      { column: "0", row: "B", price: "60,000 تومان", status: "unavailable" },
      { column: "0", row: "B", price: "60,000 تومان", status: "unavailable" },
      { column: "7", row: "B", price: "60,000 تومان", status: "available" },
      { column: "8", row: "B", price: "60,000 تومان", status: "available" },
      { column: "9", row: "B", price: "60,000 تومان", status: "available" },
      { column: "10", row: "B", price: "60,000 تومان", status: "available" },
      { column: "11", row: "B", price: "60,000 تومان", status: "available" },
      { column: "12", row: "B", price: "60,000 تومان", status: "available" },
      { column: "13", row: "B", price: "60,000 تومان", status: "available" },
      { column: "14", row: "B", price: "60,000 تومان", status: "available" },
      { column: "15", row: "B", price: "60,000 تومان", status: "available" },
      { column: "16", row: "B", price: "60,000 تومان", status: "available" },
      { column: "17", row: "B", price: "60,000 تومان", status: "available" },
      { column: "18", row: "B", price: "60,000 تومان", status: "available" },
      { column: "19", row: "B", price: "60,000 تومان", status: "available" },
      { column: "20", row: "B", price: "60,000 تومان", status: "available" },
      { column: "21", row: "B", price: "60,000 تومان", status: "available" },
      { column: "22", row: "B", price: "60,000 تومان", status: "available" },
      { column: "23", row: "B", price: "60,000 تومان", status: "available" },
      { column: "0", row: "B", price: "60,000 تومان", status: "unavailable" },
      { column: "0", row: "B", price: "60,000 تومان", status: "unavailable" },
      { column: "0", row: "A", price: "60,000 تومان", status: "unavailable" },
      { column: "2", row: "A", price: "60,000 تومان", status: "available" },
      { column: "3", row: "A", price: "60,000 تومان", status: "available" },
      { column: "4", row: "A", price: "60,000 تومان", status: "available" },
      { column: "5", row: "A", price: "60,000 تومان", status: "available" },
      { column: "6", row: "A", price: "60,000 تومان", status: "available" },
      { column: "7", row: "A", price: "60,000 تومان", status: "available" },
      { column: "8", row: "A", price: "60,000 تومان", status: "available" },
      { column: "9", row: "A", price: "60,000 تومان", status: "available" },
      { column: "10", row: "A", price: "60,000 تومان", status: "available" },
      { column: "11", row: "A", price: "60,000 تومان", status: "available" },
      { column: "12", row: "A", price: "60,000 تومان", status: "available" },
      { column: "13", row: "A", price: "60,000 تومان", status: "available" },
      { column: "14", row: "A", price: "60,000 تومان", status: "available" },
      { column: "15", row: "A", price: "60,000 تومان", status: "available" },
      { column: "16", row: "A", price: "60,000 تومان", status: "available" },
      { column: "17", row: "A", price: "60,000 تومان", status: "available" },
      { column: "18", row: "A", price: "60,000 تومان", status: "available" },
      { column: "19", row: "A", price: "60,000 تومان", status: "available" },
      { column: "20", row: "A", price: "60,000 تومان", status: "available" },
      { column: "21", row: "A", price: "60,000 تومان", status: "available" },
      { column: "22", row: "A", price: "60,000 تومان", status: "available" },
      { column: "23", row: "A", price: "60,000 تومان", status: "available" },
      { column: "24", row: "A", price: "60,000 تومان", status: "available" },
      { column: "25", row: "A", price: "60,000 تومان", status: "available" },
    ],
  },
];

export const Date = [
  { day: "شنبه", date: "13 آبان" },
  { day: "یکشنبه", date: "14 آبان" },
  { day: "دوشنبه", date: "15 آبان" },
  { day: "سه شنبه", date: "16 آبان" },
  { day: "چهارشنبه", date: "17 آبان" },
  { day: "پنجشنبه", date: "18 آبان" },
  { day: "جمعه", date: "19 آبان" },
  { day: "شنبه", date: "20 آبان" },
  { day: "یکشنبه", date: "21 آبان" },
  { day: "دوشنبه", date: "22 آبان" },
  { day: "سه شنبه", date: "23 آبان" },
  { day: "چهارشنبه", date: "24 آبان" },
  { day: "پنجشنبه", date: "25 آبان" },
  { day: "جمعه", date: "26 آبان" },
  { day: "شنبه", date: "27 آبان" },
  { day: "یکشنبه", date: "28 آبان" },
  { day: "دوشنبه", date: "29 آبان" },
  { day: "سه شنبه", date: "30 آبان" },
  { day: "چهارشنبه", date: "1 آذر" },
  { day: "پنجشنبه", date: "2 آذر" },
  { day: "جمعه", date: "3 آذر" },
];

export const Cities = [
  "همه شهر‌ها",
  "تهران",
  "مشهد",
  "اصفهان",
  "شیراز",
  "کرج",
  "قم",
  "گرگان",
  "قزوین",
  "زنجان",
  "تبریز",
  "اهواز",
  "همدان",
  "سنندج",
  "زاهدان",
  "کاشان",
  "اردبیل",
  "اراک",
  "نیشابور",
  "بوشهر",
  "بابل",
  "ساری",
  "رامسر",
  "آبادان",
  "کرمانشاه",
  "بروجرد",
  "بیرجند",
  "رفسنجان",
  "اسکو",
  "سبزوار",
  "ملایر",
  "خوی",
  "یزد",
  "شاهرود",
  "رشت",
  "بهبهان",
  "ارومیه",
  "خرم آباد",
  "کرمان",
  "اندیمشک",
];

export const possibilities = [
  { possibility: "آسانسور", icon: faElevator },
  { possibility: "پارکینگ", icon: faSquareParking },
  { possibility: "بوفه", icon: faIceCream },
  { possibility: "رستوران", icon: faUtensils },
  { possibility: "کارواش", icon: faCar },
  { possibility: "کارتخوان", icon: faCreditCard },
  { possibility: "چاپ بلیت", icon: faTicket },
  { possibility: "دسترس پذیر", icon: faWheelchair },
  { possibility: "عابربانک", icon: faBuildingColumns },
  { possibility: "کافی‌شاپ", icon: faMugSaucer },
  { possibility: "کتابخانه", icon: faBook },
  { possibility: "فودکورت", icon: faHamburger },
  { possibility: "اینترنت رایگان", icon: faWifi },
  { possibility: "فروشگاه", icon: faCartShopping },
];
export const cinemaData = [
  {
    name: "پردیس سینمایی کورش",
    location: "اتوبان حکیم غرب، ستاری شمال، جنب پیامبر مرکزی",
    ratePoint: 3.6,
    rateNum: 6343,
    possibilities: [
      "آسانسور",
      "پارکینگ",
      "بوفه",
      "رستوران",
      "کارواش",
      "کارتخوان",
      "چاپ بلیت",
      "دسترس پذیر",
      "عابربانک",
      "کافی‌شاپ",
      "کتابخانه",
      "فودکورت",
      "اینترنت رایگان",
    ],
    salons: [
      "گراند سینما(1)",
      "فاروس(2)",
      "لاله زار(3)",
      "خورشیدنو(5)",
      "نادر(6)",
      "متروپل(10)",
      "رکس(11)",
      "ایران(12)",
    ],
  },
  {
    name: "پردیس سینمایی ایران مال",
    location: "اتوبان شهید همت غرب، اتوبان شهید خرازی، بازار بزرگ ایران",
    ratePoint: 4,
    rateNum: 1684,
    possibilities: [
      "آسانسور",
      "پارکینگ",
      "بوفه",
      "رستوران",
      "کارواش",
      "کارتخوان",
      "چاپ بلیت",
      "دسترس پذیر",
      "عابربانک",
      "کافی‌شاپ",
      "کتابخانه",
      "فودکورت",
    ],
  },
  {
    name: "پردیس سینما آزادی",
    location: "خیابان بهشتی، نبش خالد اسلامبولی(وزرا)",
    ratePoint: 3.3,
    rateNum: 3488,
    possibilities: [
      "آسانسور",
      "بوفه",
      "رستوران",
      "کارتخوان",
      "چاپ بلیت",
      "دسترس پذیر",
      "عابربانک",
      "کافی‌شاپ",
      "فودکورت",
      "اینترنت رایگان",
    ],
  },
  {
    name: "پردیس سینمایی پرده طلایی",
    location:
      "تهران، آیت الله سعیدی، شهرک ولیعصر، خیابان مهر، جنب بازار بزرگ ولیعصر",
    ratePoint: 4.7,
    rateNum: 101,
    possibilities: [],
  },
  {
    name: "پردیس سینمایی مگامال",
    location: "شهرک اکباتان، فاز۲ ",
    ratePoint: 3.7,
    rateNum: 3139,
    possibilities: [
      "آسانسور",
      "پارکینگ",
      "بوفه",
      "کارواش",
      "کارتخوان",
      "چاپ بلیت",
      "دسترس پذیر",
      "عابربانک",
      "کافی‌شاپ",
      "کتابخانه",
      "فودکورت",
      "اینترنت رایگان",
    ],
  },
  {
    name: "پردیس سینمایی شمیران",
    location: "اقدسیه، بزرگراه ارتش، مجموعه شمیران سنتر، طبقه۳",
    ratePoint: 3.3,
    rateNum: 3488,
    possibilities: [
      "آسانسور",
      "پارکینگ",
      "بوفه",
      "رستوران",
      "کارتخوان",
      "چاپ بلیت",
      "دسترس پذیر",
      "عابربانک",
      "کافی‌شاپ",
      "فودکورت",
    ],
  },
  {
    name: "پردیس سینمایی مرداس",
    location: "خیابان جمهوری، روبروی باغ سپهسالار",
    ratePoint: 2.3,
    rateNum: 24,
    possibilities: ["پارکینگ"],
  },
  {
    name: "پردیس سینمایی چارسو",
    location: "خیابان جمهوری، تقاطع حافظ",
    ratePoint: 3.7,
    rateNum: 2945,
    possibilities: [
      "پارکینگ",
      "کارتخوان",
      "چاپ بلیت",
      "عابربانک",
      "کافی‌شاپ",
      "فودکورت",
    ],
  },
  {
    name: "پردیس سینمایی معین مال",
    location:
      "ابتدای خیابان آزادی، ابتدای خیابان استاد معین، مجتمع تجاری معین مال",
    ratePoint: 4.4,
    rateNum: 167,
    possibilities: [
      "آسانسور",
      "پارکینگ",
      "بوفه",
      "کارتخوان",
      "چاپ بلیت",
      "دسترس پذیر",
      "عابربانک",
      "کافی‌شاپ",
      "کتابخانه",
      "فودکورت",
    ],
  },
  {
    name: "پردیس سینما گالری ملت",
    location:
      "خیابان ولیعصر، بزرگراه هاشمی رفسنجانی(نیایش)، روبری بزرگراه کردستان",
    ratePoint: 3.3,
    rateNum: 2059,
    possibilities: [
      "آسانسور",
      "پارکینگ",
      "کارتخوان",
      "چاپ بلیت",
      "دسترس پذیر",
      "عابربانک",
      "کافی‌شاپ",
      "فودکورت",
    ],
  },
];
export const Salons = [
  {
    salonName: "گراند سینما(1)",
    id: 900,
    date: "13 آبان",
    time: ["11:00", "13:10", "15:20", "17:30", "19:40", "21:50", "23:59"],
  },
  {
    salonName: "فاروس(2)",
    id: 901,
    date: "13 آبان",
    time: ["11:00", "13:10", "15:20", "17:30", "19:40", "21:50", "23:59"],
  },
  {
    salonName: "لاله زار(3)",
    id: 902,
    date: "13 آبان",
    time: ["11:00", "13:10", "15:20", "17:30", "19:40", "21:50", "23:59"],
  },
  {
    salonName: "خورشیدنو(5)",
    id: 903,
    date: "13 آبان",
    time: ["11:00", "13:10", "15:20", "17:30", "19:40", "21:50", "23:59"],
  },
  {
    salonName: "نادر(6)",
    id: 904,
    date: "13 آبان",
    time: ["11:00", "13:10", "15:20", "17:30", "19:40", "21:50", "23:59"],
  },
  {
    salonName: "متروپل(10)",
    id: 904,
    date: "13 آبان",
    time: ["11:00", "13:10", "15:20", "17:30", "19:40", "21:50", "23:59"],
  },
  {
    salonName: "رکس(11)",
    id: 906,
    date: "13 آبان",
    time: ["11:00", "13:10", "15:20", "17:30", "19:40", "21:50", "23:59"],
  },
  {
    salonName: "ایران(12)",
    id: 907,
    date: "13 آبان",
    time: ["11:00", "13:10", "15:20", "17:30", "19:40", "21:50", "23:59"],
  },
  {
    salonName: "گراند سینما(1)",
    id: 908,
    date: "14 آبان",
    time: ["11:00", "13:10", "15:20", "17:30", "19:40", "21:50", "23:59"],
  },
];

// export const Movie = [
//   {
//     section: "فیلم ایرانی",
//     name: "هتل",
//     director: "سید مسعود اطیابی",
//     genre: "کمدی",
//     rate: "۴.۳",
//     view: "۶۳",
//     amount: "19,382,500,500",
//     description:
//       "فیلم هتل به کارگردانی مسعود اطیابی و تهیه‌کنندگی محمد شایسته با بازی پژمان جمشیدی، محسن کیایی است. ریما رامین‌فر، صدف اسپهبدی، مهلقا باقری، غلامرضا نیکخواه، مریم وحیدزاده، فرزانه قاسم‌زاده، جواد پولادی و سام نوری نیز سایر بازیگران هتل هستند.",
// synopsis :" خلاصه داستان: کی بهشت رو ول می‌کنه بره جهنم؟!",
//     actorName1: "پژمان جمشیدی",
//     actorName2: "محسن کیایی",
//     actorName3: "صدف اسپهبدی",
//     actorName4: "ریما رامین فر",
//     actorName5: "مه‌لقا باقری",
//     actorName6: "غلامرضا نیکخواه",
//     actorName7: "مریم وحیدزاده",
//     actorName8: "فرزانه قاسم زاده",
//     actorName9: "جواد پولادی",
//     actorName10: "سام نوری",
//   },
//   {
//     section: "فیلم ایرانی",
//     name: "بچه زرنگ",
//     genre: "ماجراجویی | کودک و نوجوان",
//     rate: "۴.۷",
//     view: "۲۰",
//     time: "۸۵",
//     amount: "10,310,468,422",
//     description:
//       "انیمیشن بچه زرنگ ساخته گروه هنرپویا درباره‌ ماجرای پسر بچه‌ای به نام محسن است که خود را ابرقهرمان می‌داند و در یک اتفاق نادر، به جنگلی اسرار آمیز قدم می‌گذارد و با حیوانات منقرض شده ایران مواجه می‌شود… این آغاز یک ماجرای پیچیده برای نجات آخرین ببر ایرانی. فیلم انیمیشنی بچه زرنگ ساخته گروه هنرپویا گروه هنر پویا به تهیه‌کنندگی حامد جعفری است. صداپیشگان این فیلم عبارت‌اند از: سعید شیخ‌زاده، هومن حاجی‌عبداللهی، هدایت هاشمی، میرطاهر مظلومی، ژرژ پطروسی، جواد پزشکیان، مینا قیاس‌پور، مریم رادپور، تورج نصر، اردشیر منظم، مهسا عرفانی، ابراهیم شفیعی، همت مومی‌وند، .شایان شامبیاتی، حسن کاخی، امیر حکیمی، نازنین یاری، علیرضا دیباج، متانت اسماعیلی، پویا فهیمی.    ",
//     actorName1: "هومن حاجی عبداللهی",
//     actorName2: "سعید شیخ زاده",
//     actorName3: "هدایت هاشمی",
//     actorName4: "میرطاهر مظلومی",
//     actorName5: "ژرژ پطروسی",
//   },
//   {
//     section: "فیلم ایرانی",
//     name: "بی مادر",
//     director: "سید مرتضی فاطمی",
//     genre: "اجتماعی",
//     rate: "۳.۶",
//     view: "۴۱۴",
//     time: "۸۵",
//     amount: "9,546,462,010",
//     description:
//       "فیلم بی مادر به کارگردانی سیدمرتضی فاطمی و تهیه‌کنندگی محمدرضا مصباح و علی اوجی در ژانر اجتماعی ساخته شده است. بی مادر با حضور در چندین جشنواره معتبر بین‌المللی از جمله جشنواره بین‌المللی فیلم داکا، جشنواره‌‌ بین‌المللی‌ بنگلور، جشنواره کراسینگ اسکرین و جشنواره رینبو لندن، موفق به کسب جوایز متعددی شده است. در این فیلم بازیگرانی همچون امیر آقایی، پژمان جمشیدی، میتراحجار به ایفای نقش پرداخته‌اند. برخی از عوامل فیلم عبارت‌اند از: مدیر فیلمبرداری: مسعود سلامی، چهره‌پرداز: محمود دهقانی، طراح صحنه: سهیل دانش اشراقی، تدوین:‌ محمد نجاریان، بهرام دهقانی، صدابردار: بابک اردلان.",
// synopsis :" خلاصه داستان: زندگی آرام یک زوج با پافشاری یکی از آنها روی تصمیمش، ناخواسته وارد دو راهی‌ها و مخاطرات اخلاقی پیچیده‌ای می‌شود.",
//     actorName1: "امیر آقایی",
//     actorName2: "پژمان جمشیدی",
//     actorName3: "میترا حجاز",
//     actorName4: "پردیس پورعابدینی",
//     actorName5: "علی اوجی",
//     actorName6: "سارا محمدی",
//     actorName7: "بیتا عزیزاوقلو",
//   },
//   {
//     section: "فیلم ایرانی",
//     name: "نارگیل ۲",
//     director: "داود اطیابی",
//     genre: "کمدی",
//     rate: "۳.۶",
//     view: "۱۳۳",
//     time: "۸۰",
//     amount: "11,112,523,100",
//     description:
//       "فیلم نارگیل 2 به کارگردانی سیدداود اطیابی و تهیه‌کنندگی سیدابراهیم عامریان است که ژانری کمدی دارد. بیژن بنفشه‌خواه، علیرضا استادی، سحر قریشی، شقایق دهقان، نصرالله رادش و غلامحسین لطفی بازیگران اصلی این فیلم هستند.",
//     actorName1: "غلامحسین لطفی",
//     actorName2: "بیژن بنفشه خواه",
//     actorName3: "علیرضا استادی",
//     actorName4: "سحر قریشی",
//     actorName5: "شقایق دهقان",
//     actorName6: "نصرالله رادش",
//     actorName7: "امید روحانی",
//     actorName8: "مانیا علیجانی",
//     actorName9: "آرین اسماعیلی",
//   },
//   {
//     section: "فیلم ایرانی",
//     name: "بعد از رفتن",
//     director: "رضا نجاتی",
//     genre: "درام",
//     rate: "۲.۸",
//     view: "۶۱",
//     amount: "19,681,419,000",
//     description:
//       "فیلم بعد از رفتن به کارگردانی رضا نجاتی و تهیه‌کنندگی محمود بابایی است. صابر ابر، سارا بهرامی، پوریا رحیمی‌سام، پانته‌آ پناهی‌ها، بهرام شاه‌محمدلو، احترام برومند و ... بازیگران این فیلم هستند.",
// synopsis :" خلاصه داستان: آرش بعد از مدت‌ها دوری به زادگاهش باز می‌گردد و به دنبال گمشده‌اش است…    ",
//     actorName1: "صابر ابر",
//     actorName2: "سارا بهرامی",
//     actorName3: "پوریا رحیمی سام",
//     actorName4: "پانته آ پناهی‌ها",
//     actorName5: "بهرام شاه محمدلو",
//     actorName6: "احترام برومند",
//     actorName7: "روشنک گرامی",
//     actorName8: "یسنا میرطهماسب",
//     actorName9: "خسرو احمدی",
//     actorName10: "حامی ترابی",
//   },
//   {
//     section: "فیلم ایرانی",
//     name: "شهر هرت",
//     director: "کریم امینی",
//     genre: "کمدی",
//     rate: "۲.۹",
//     view: "۸۰۴",
//     time: "۹۵",
//     amount: "65,254,900,125",
//     description:
//       "فیلم شهر هرت به کارگردانی کریم امینی و تهیه‌کنندگی محمدحسین فرح‌بخش است و ژانری کمدی دارد. پژمان جمشیدی، شبنم مقدمی و بابک کریمی بازیگران اصلی این فیلم را شامل می‌شوند.    ",
//     actorName1: "پژمان جمشیدی",
//     actorName2: "شبنم مقدمی",
//     actorName3: "بابک کریمی",
//     actorName4: "اکبر رحمتی",
//   },
//   {
//     section: "فیلم ایرانی",
//     name: "هولیا",
//     director: "مرتضی آتش زمزم",
//     genre: "کمدی",
//     rate: "۲.۹",
//     view: "۱۴۲",
//     amount: "5,676,878,320",
//     description:
//       "فیلم کمدی موزیکال هولیا به کارگردانی مرتضی آتش‌زمزم است که در آن بازیگرانی همچون پوریا پورسرخ، محمد رضا هدایتی، علی انصاریان، مریم امیرجلالی و بهراد خرازی ایفای نقش کرده‌اند.    ",
//     actorName1: "پوریا پورسرخ",
//     actorName2: "محمدرضا هدایتی",
//     actorName3: "علی انصاریان",
//     actorName4: "مریم امیرجلالی",
//     actorName5: "بهراد خرازی",
//     actorName6: "محمد فیلی",
//     actorName7: "افشین سنگ چاپ",
//     actorName8: "مجید شهریاری",
//     actorName9: "شراره رخام",
//     actorName10: "شیوا خسرومهر",
//     actorName11: "شیوا طاهری",
//     actorName12: "مهدی امینی خواه",
//     actorName13: "مهدی امینی",
//     actorName14: "علی کوچولو",
//     actorName15: "مهدی حسینی",
//     actorName16: "مریم نقیب",
//     actorName17: "هدی استواری",
//     actorName18: "شیما جوهری",
//     actorName19: "مسعود حقی",
//   },
//   {
//     section: "فیلم ایرانی",
//     name: "فسیل",
//     director: "کریم امینی",
//     genre: "کمدی",
//     rate: "۴.۵",
//     view: "۳۷۰۵",
//     amount: "263,657,031,014",
//     description:
//       "فیلم فسیل به کارگردانی کریم امینی و تهیه‌کنندگی ابراهیم عامریان است. بهرام افشاری، هادی کاظمی، الناز حبیبی، الهه حصاری، ایمان صفا، بابک کریمی، سیدجواد هاشمی و ... در این فیلم کمدی ایفای نقش کرده‌اند. خلاصه فیلم: با فسيل به دهه پنجاه سفر كنيد...    ",
//     actorName1: "بهرام افشاری",
//     actorName2: "هادی کاظمی",
//     actorName3: "الناز حبیبی",
//     actorName4: "الهه حصاری",
//     actorName5: "ایمان صفا",
//     actorName6: "بابک کریمی",
//     actorName7: "سید جواد هاشمی",
//     actorName8: "غلامرضا نیکخواه",
//     actorName9: "سمانه منیری",
//     actorName10: "امید روحانی",
//     actorName11: "علیرضا استادی",
//     actorName12: "قاسم زارع",
//     actorName13: "خشایار راد",
//     actorName14: "مجید شهریاری",
//   },
//   {
//     section: "فیلم ایرانی",
//     name: "زنبور کارگر",
//     director: "افشین صادقی",
//     genre: "اجتماعی",
//     rate: "۳.۳",
//     view: "۴۷",
//     amount: "4,532,879,012",
//     description:
//       "فیلم زنبور کارگر به کارگردانی و تهیه‌کنندگی افشین صادقی و نویسندگی سعید نعمت‌الله است. حمید فرخ‌نژاد، شبنم مقدمی، سعید آقاخانی، پگاه آهنگرانی، حسن مهری و ... بازیگران این فیلم را شامل می‌شوند.    ",
//   },
//   {
//     section: "فیلم ایرانی",
//     name: "آخرین تولد",
//     director: "نوید محمودی",
//     genre: "درام",
//     rate: "۲.۷",
//     view: "۱۷۳",
//     time: "۸۵",
//     amount: "8,666,020,158",
//     description:
//       "فیلم آخرین تولد به کارگردانی و نویسندگی نوید محمودی و تهیه‌کنندگی جمشید محمودی است. الناز شاکردوست، پدرام شریفی، شیدا خلیق، آرمین رحیمیان، سوگل خلیق، نیلوفر کوخانی و رضا بهبودی بازیگران این فیلم را شامل می‌شوند.",
// synopsis :" خلاصه داستان: روایتی از عشق ثریا و فهیم؛ عشقی که سایه‌ جنگ بر سرش آوار شده است، غزلی است عاشقانه در دل بحران...    ",
//     actorName1: "الناز شاکردوست",
//     actorName2: "پدرام شریفی",
//     actorName3: "شیدا خلیق",
//     actorName4: "آرمین رحیمیان",
//     actorName5: "سوگل خلیق",
//     actorName6: "نیلوفر کوخانی",
//     actorName7: "رضا بهبودی",
//   },
//   {
//     section: "فیلم ایرانی",
//     name: "شماره ۱۰",
//     director: "حمید زرگرنژاد",
//     genre: "دفاع مقدس",
//     rate: "۴.۰",
//     view: "۳۳",
//     amount: "10,022,156,008",
//     description:
//       "فیلم شماره 10 به نویسندگی و کارگردانی حمید زرگرنژاد و تهیه‌کنندگی ابراهیم اصغری است. در این فیلم بازیگرانی همچون مجید صالحی، حسام منظور، سیامک صفری و صحرا اسداللهی ایفای نقش می‌کنند.",
// synopsis :" خلاصه داستان: فرار از اینجا بهترین راهه چون همه‌مون ازش می‌ترسیم…    ",
//     actorName1: "مجید صالحی",
//     actorName2: "حسام منظور",
//     actorName3: "سیامک صفری",
//     actorName4: "مهدی زمین پرداز",
//     actorName5: "بهرنگ علوی",
//     actorName6: "صحرا اسداللهی",
//     actorName7: "احمد کاوری",
//   },
//   {
//     section: "فیلم ایرانی",
//     name: "ستاره بازی",
//     director: "هاتف علیمردانی",
//     genre: "اجتماعی",
//     rate: "۳.۳",
//     view: "۱۸۱",
//     amount: "3,649,284,165",
//     description:
//       "فیلم ستاره بازی به کارگردانی و نویسندگی هاتف علیمردانی و تهیه‌کنندگی علی سرتیپی است. در این فیلم بازیگرانی چون فرهاد اصلانی، شبنم مقدمی، ملیسا ذاکری، علی مصفا و مایکل مدسن ستاره سینمای آمریکا به همراه مارشال منش، لیندا جویز، هاوارد رسنزتین و دان لیستر ایفای نقش کرده‌اند.",
// synopsis :" خلاصه داستان: امروز بیست‌و‌نه نوامبره، از اون هالووین لعنتی یه ماه می‌گذره، من یه کار بد کردم، یه کار خیلی بد...    ",
//     actorName1: "فرهاد اصلانی",
//     actorName2: "شبنم مقدمی",
//     actorName3: "ملیسا ذاکری",
//     actorName4: "علی مصفا",
//     actorName5: "مایکل مدسن",
//     actorName6: "مارشال منش",
//     actorName7: "لیندا جویز",
//     actorName8: "هاوارد رسنزتین",
//     actorName9: "دان لیستر",
//   },
//   {
//     section: "فیلم ایرانی",
//     name: "ستون ۱۴",
//     director: "امیرحسین همتی",
//     genre: "اجتماعی",
//     rate: "۳.۴",
//     view: "۲۰۲",
//     time: "۹۵",
//     amount: "1,645,899,423",
//     description:
//       "ستون 14 به کارگردانی و نویسندگی امیرحسین همتی است که در آن بازیگرانی همچون میترا حجار، روزبه حصاری، میلاد رحیمی، مهسا باقری و علی میلانی ایفای نقش می‌کنند. این فیلم توسط علیرضا قاسم‌خان تهیه‌کنندگی شده است. دیگر عوامل ستون 14 عبارت‌اند از: فیلمبردار: مسعود امینی تیرانی، مجری طرح و مدیر تولید: سید احمد ساکت، مشاور کارگردان: احمد امینی، طراحی و ترکیب صدا: ندا محسنی، تدوین: پرهام وفایی، صدابردار: شهرام متولی‌باشی، موسیقی: مهدی محمود‌خانی، طراح گریم: الهام صالحی، طراح صحنه: امیرحسین همتی.",
// synopsis :" خلاصه داستان: ساناز و یاشار وقتی می‌ترسند، بازی می‌کنند. این‌بار با زندگی جلال …    ",
//     actorName1: "میترا حجاز",
//     actorName2: "روزبه حصاری",
//     actorName3: "میلاد رحیمی",
//     actorName4: "مهسا باقری",
//     actorName5: "علی میلانی",
//   },
//   {
//     section: "فیلم ایرانی",
//     name: "دست انداز",
//     director: "کمال تبریزی",
//     genre: "درام",
//     rate: "۳.۱",
//     view: "۱۲۷",
//     time: "۸۴",
//     amount: "2,654,852,111",
//     description:
//       "فیلم دست انداز به کارگردانی کمال تبریزی، نویسندگی فرزاد فخری‌زاده و تهیه‌کنندگی محمد آفریده است. امید نعمتی، هدی زین‌العابدین، رویا نونهالی رضا کیانیان بازیگران اصلی این فیلم را شامل می‌شوند.",
// synopsis :" خلاصه داستان: رها که علاقه‌مند به نویسندگی است آخرین داستان خود را با آرزوهایش همراه می‌کند.    ",
//     actorName1: "رضا کیانیان",
//     actorName2: "امید نعمتی",
//     actorName3: "هدی زین العابدین",
//     actorName4: "حبیب رضایی",
//     actorName5: "همایون ارشادی",
//     actorName6: "رویا نونهالی",
//     actorName7: "محمدرضا حسین زاده",
//   },
//   {
//     section: "فیلم ایرانی",
//     name: "کت چرمی",
//     director: "حسین میرزامحمدی",
//     genre: "درام | معمایی",
//     rate: "۳.۲",
//     view: "۵۱۸",
//     amount: "14,422,684,250",
//     description:
//       "فیلم کت چرمی به کارگردانی حسین میرزامحمدی، نویسندگی مسعود هاشمی‌نژاد و محصول سال 1401 است. جواد عزتی، صابر ابر، گلاره عباسی، پانته‌آ پناهی‌ها و ستاره پسیانی بازیگران اصلی این فیلم هستند. برخی از عوامل کت چرمی عبارت‌اند از: مجری طرح: پیمان حجازی، مدیر فیلمبرداری: آرمان فیاض، تدوین: عماد خدابخش، آهنگساز: مسعود سخاوت دوست، مدیرتولید: پیمان حمیدی، مدیر صدابرداری: محمد شاهوردی، طراحی و ترکیب صدا: آرش قاسمی، طراح صحنه: بهزاد جعفری طادی. خلاصه فیلم: عیسی فرهمند، کارمند بازرسی سازمان بهزیستی در جریان بازدید از یک مرکز نگهداری دختران خیابانی، متوجه باند فساد مشکوکی می‌شود که او را به یک مهمانی زیرزمینی ممنوعه می‌رساند‌؛ مهمانی کُت‌چرمی ...    ",
//     actorName1: "جواد عزتی",
//     actorName2: "صابر ابر",
//     actorName3: "گلاره عباسی",
//     actorName4: "پانته آ پناهی ها",
//     actorName5: "ستاره پسیانی",
//     actorName6: "عباس جمشیدی‌فر",
//     actorName7: "مائده طهماسبی",
//     actorName8: "بهزاد خلج",
//     actorName9: "امین میری",
//     actorName10: "محمد صدیقی مهر",
//     actorName11: "آیدا ماهیانی",
//     actorName12: "سارا حاتمی",
//     actorName13: "رویا تیموریان",
//     actorName14: "سیامک احصایی",
//   },
//   {
//     section: "کودک و نوجوان",
//     name: "لب خنده",
//     director: "آرش ابراهیم زاده",
//     genre: "کودک",
//     rate: "۵",
//     view: "۱۳",
//     description:
//       "نمایش لب خنده به نویسندگی و کارگردانی آرش ابراهیم‌زاده است که از 20 تیر تا 20 مهر در پردیس سینمایی هدیش‌مال اجرا می‌شود. محمد سروش‌فر، جواد سلیمانی، رامبد پورمفخمی، ملیکا حسینی، کیانا تعصبی و ... بازیگران این نمایش هستند. خلاصه نمایش: حسینقلی پسری که با سفر پدرش دلتنگ شده بود و مدام گریه می‌کرد و نمی‌خندید، برای به دست آوردن لب خنده‌اش سفری خیالی را شروع می‌کند تا بتواند به شادی و خنده حقیقی برسد...    ",
//   },
//   {
//     section: "کودک و نوجوان",
//     name: "فیلم انیمیشن لوکا (Luca)",
//     director: "انریکو کاساروسا",
//     genre: "کودک و نوجوان | دوبله",
//     rate: "۴.۶",
//     view: "۳۴",
//     time: "۹۶",
//     description:
//       "انیمیشن لوکا یک انیمیشن تخیلی محصول شرکت انیمیشن سازی پیکسار است. کارگردانی این فیلم بر عهده انریکو کاساروسا بوده است و در این فیلم جیکوب ترمبلی، جک دیلان گریزر، اما برمن، ساوریو رایموندو، مایا رودولف، مارکو باریکلی و جیم گفین صداپیشگی می‌کنند. این فیلم در سال 2021 ساخته و اکران شد و مدت زمان این فیلم 95 دقیقه است. خلاصه فیلم: در ریوریای ایتالیا، یک دوستی عجیب و قوی بین یک انسان و یک غول دریایی که انسان‌ها فراری است شکل می‌گیرد.    ",
//   },
//   {
//     section: "کودک و نوجوان",
//     name: "بابا سیبیلو",
//     director: "ادوین خاچیکیان",
//     genre: "کودک",
//     rate: "۲.۶",
//     view: "۴۴",
//     description:
//       "فیلم بابا سیبیلو به کارگردانی ادوین خاچیکیان و تهیه‌کنندگی احمد احمدی است. این فیلم ژانری کمدی-خانوادگی دارد و بازیگرانی همچون رضا شفیعی‌جم، بهاره رهنما، امیرحسین صدیق و عباس محبوب در آن ایفای نقش کرده‌اند.    ",
//   },
//   {
//     section: "کودک و نوجوان",
//     name: "آرزوی الاغ",
//     director: "محمدحسین داداش نیا",
//     genre: "کودک و نوجوان",
//     rate: "۵",
//     view: "۱",
//     time: "۵۵",
//     description:
//       "نمایش آرزوی الاغ به کارگردانی و نویسندگی محمدحسین داداش‌نیاست که از 3 مهر تا 3 آبان در فرهنگسرای فردوس اجرا می‌شود. محمدحسین داداش‌نیا، نرگس نیک‌سیرت، مریم اسکندری، بهاره رمه‌چی و پروا نریمانی بازیگران این نمایش هستند.",
// synopsis :" خلاصه داستان: الاغ آرزو می‌کند تا مثل یک پروانه باشد ولی بر اساس ماجرایی متوجه می‌شود که باید به الاغ بودنش افتخار کند.    ",
//   },
//   {
//     section: "کودک و نوجوان",
//     name: "نیم وجبی",
//     director: "علیرضا دهقانی",
//     genre: "کودک و نوجوان",
//     rate: "۲.۵",
//     view: "۴",
//     time: "۵۰",
//     description:
//       "نمایش نیم وجبی از 10 تا 31 مرداد در فرهنگسرای فردوس اجرا می‌شود.    ",
//   },
//   {
//     section: "کودک و نوجوان",
//     name: "خاله‌سوسکه",
//     genre: "کودک و نوجوان",
//     rate: "۲.۷",
//     description:
//       "نمایش خاله سوسکه به نویسندگی و کارگردانی مهرداد قرآن‌کیش است که در فرهنگسرای ابن‌سینا اجرا می‌شود.    ",
//   },
//   {
//     section: "کودک و نوجوان",
//     name: "بل و شاهزاده‌ مغرور",
//     director: "علیرضا دهقانی",
//     genre: "کودک و نوجوان",
//     rate: "۵",
//     view: "۳",
//     time: "۵۰",
//     description:
//       "نمایش بل و شاهزاده مغرور به کارگردانی علیرضا دهقانی و نویسندگی ماندانا عبقری است که از 28 شهریور تا 28 مهر در پردیس تئاتر شهرزاد می‌شود. ماندانا عبقری، دیار باغی، محمدرضا لطفی، هادی شبانی، لیلا احمدی و بهار حسین زادگان در این نمایش نقش‌آفرینی کرده‌اند.",
// synopsis :" خلاصه داستان: در قصری زیبا شاهزاده‌ای مغرور و بدخلق زندگی می‌کند، شبی طوفانی جادوگری به قصر پناه می‌برد اما شاهزاده او را به قصر راه نمی‌دهد. جادوگر شاهزاده و خدمتکارانش را جادو می‌کند، شاهزاده به موجودی عجیب تبدیل می‌شود.    ",
//   },
//   {
//     section: "تئاتر",
//     name: "اسکرین شات",
//     director: "امیر عباسی",
//     genre: "تئاتر",
//     rate: "۴.۵",
//     view: "۱۰",
//     time: "۶۰",
//     description:
//       "اسکرین شات به کارگردانی امیر عباسی و نویسندگی و تهیه‌کنندگی سامان شمس است که از 28 تیر تا 27 مرداد در پردیس تئاتر شهرزاد (سالن سه) اجرا می‌شود. امیرحسین رضازاده، حامد آرامی، امیرحسین همایونی، ستاره فلاح‌فرد، سحر قلباروند، حسین جاهد، رومینا کوهزاد و مرضیه ابراهیمی بازیگران این نمایش هستند.",
// synopsis :" خلاصه داستان: فرض کنید در یک دورهمی در کنار همسر و دوستانتان، مجبور شوید تمام محتویات تلفن همراهتان را با صدای بلند بخوانید.    ",
//   },
//   {
//     section: "تئاتر",
//     name: "سه شب با مادوکس",
//     director: "شیوا دیناروند",
//     genre: "تئاتر",
//     rate: "۵",
//     view: "۱",
//     time: "۶۰",
//     description:
//       "نمایش سه شب با مادوکس به کارگردانی شیوا دیناروند و تهیه‌کنندگی او با مجید یارندی پور است که از 29 شهریور تا 25 مهر در تالار حافظ اجرا می‌شود. مسعود کرامتی، بهاره رهنما، سیدجواد یحیوی، وحید نفر و میلاد رمضانی بازیگران این نمایش هستند.",
// synopsis :" خلاصه داستان: شخص مرموزی به نام مادوکس در شهری حاضر شده و ساکنان شهر به وحشت افتاده‌اند.    ",
//   },
//   {
//     section: "تئاتر",
//     name: "پدر",
//     director: "آروند دشت آرای",
//     genre: "تئاتر",
//     time: "۸۰",
//     description:
//       "نمایش پدر به کارگردانی آروند دشت آرای و تهیه‌‎کنندگی محمد قدس است که از 17 مهر تا 26 آبان در سالن اصلی تئاتر شهر اجرا می‌شود. رضا کیانیان، مارین ون هولک، سعید چنگیزیان، سوگل خلیق، بهزاد کریمی و پریسا شاه‌ولیان بازیگران این نمایش هستند.",
// synopsis :" خلاصه داستان: «پدر» تجربه‌ای دردناک و بکری است از زوال عقل (آلزایمر)، که به وضعیت او و ارتباط با دخترش می‌پردازد.    ",
//   },
//   {
//     section: "تئاتر",
//     name: "کانال",
//     director: "مرتضی فروزان فر",
//     genre: "تئاتر",
//     rate: "۱.۰",
//     view: "۱",
//     time: "۷۰",
//     description:
//       "نمایش کانال به نویسندگی و کارگردانی مرتضی فروزان‌فر و تهیه‌کنندگی مطهره عباسی است که از 5 تا 25 مهر در عمارت ارغوان اجرا می‌شود. شهرزاد بیانی، لیلا شاهی، محمدجواد عارف‌اصیل، سجاد حیدریه، علیرضا اتابکی، امیرحسین شیشه‌گران، حامد لطفی، امید محمدی، حمید صالحی و مرتضی فروزان‌فر بازیگران این نمایش هستند.",
// synopsis :" خلاصه داستان: جهان تک‌صدایی‌ست در رفت‌وآمد که..    ",
//   },
//   {
//     section: "تئاتر",
//     name: "کمدی گمنام",
//     director: "علی اصغری",
//     genre: "تئاتر",
//     time: "۶۰",
//     description:
//       "نمایش کمدی گمنام به کارگردانی و نویسندگی علی اصغری است که از 6 مهر تا 9 آبان در عمارت نوفل‌لوشاتو اجرا می‌شود. فرزاد حسنی و حسین پورکریمی بازیگران اصلی این نمایش هستند.",
// synopsis :" خلاصه داستان: دو دوست قدیمی و هنرور سینما در سال‌های پس از انقلاب ۱۳۵۷ گمان می‌کنند که ممنوع‌الکار شده‌اند و بدین سبب دست به هر کاری می‌زنند.    ",
//   },
//   {
//     section: "تئاتر",
//     name: "طبیب اجباری",
//     director: "سهیل جمشیدی",
//     genre: "تئاتر",
//     time: "۷۵",
//     description:
//       "نمایش طبیب اجباری به کارگردانی سهیل جمشیدی و تهیه‌کنندگی هاتف کلاته است که از 6 تا ۲۰ مهر در خانه نمایش دا اجرا می‌شود. افشین قدیمی، نازنین‌زهرا مقدسی، مریم حاج‌محمدی، محمد مغانی، عباس ستارزاده، ‌مهشید زبردست، سهیل جمشیدی و ، پویا رفیعی‌نژاد بازیگران این نمایش هستند.    ",
//   },
//   {
//     section: "تئاتر",
//     name: "بنگاه تئاترال",
//     director: "هادی مرزبان",
//     genre: "تئاتر",
//     time: "۱۰۰",
//     description:
//       "نمایش بنگاه تئاترال به کارگردانی هادی مرزبان، نویسندگی علی نصیریان و تهیه‌کنندگی مسعود والاست که از 9 تا 30 مهر در سالن 1 پردیس تئاتر شهرزاد اجرا می‌شود. مجید مظفری، علی فتحعلی، رسول نجفیان، داوود فتحعلی‌بیگی، محمود بصیری، محمدهادی عطایی و ... بازیگران این نمایش هستند.    ",
//   },
//   {
//     section: "تئاتر",
//     name: "جردن جنوبی",
//     director: "شایان مستوفی",
//     genre: "تئاتر",
//     time: "۵۰",
//     description:
//       "نمایش جردن جنوبی به نویسندگی، کارگردانی و تهیه‌کنندگی شایان مستوفی است که از 3 مهرماه در پردیس تئاتر شهرزاد اجرا می‌شود. سپهر جاویدیان، ابوالفضل حضرتی، علیرضا محمدنژاد، اسحاق طاهری، نیما امامی، شایان مستوفی و رضا شفائی بازیگران این نمایش هستند.",
// synopsis :" خلاصه داستان: شبی که منو رفیقام با دایی تنها شدیم و ...    ",
//   },
//   {
//     section: "تئاتر",
//     name: "عروس فراری",
//     director: "جواد انصافی",
//     genre: "تئاتر",
//     time: "۷۰",
//     description:
//       "نمایش عروس فراری به نویسندگی و کارگردانی جواد انصافی، تهیه‌کنندگی مهرداد وکیلی است که از 3 تا 27 مهر در پردیس تئاتر شهرزاد اجرا می‌شود. جواد انصافی، امیر پارسی، امیرمحمد و امیرحسین انصافی، رضا معراجی، فرشته اعظمی و ... بازیگران این نمایش هستند.",
// synopsis :" خلاصه داستان: مادری در اثر فقر و نبود امنیت اقتصادی قصد دارد دخترش را به عقد پیرمردی دربیاورد. دختر با کمک عبدلی و یکی از همکلاسی‌های دانشگاهی‌اش نقشه‌ای می‌کشند.    ",
//   },
//   {
//     section: "تئاتر",
//     name: "شقامک",
//     director: "سلمان سامنی",
//     genre: "تئاتر",
//     time: "۶۰",
//     description:
//       "نمایش شقامک به نویسندگی و کارگردانی سلمان سامنی است که از 2 مهر تا 1 آبان در پردیس تئاتر شهرزاد اجرا می‌شود. مهدی رضایی، لیلی صبری، رسول احمدی، کامران طاهری و المیرا صارمی بازیگران این نمایش هستند.",
// synopsis :" خلاصه داستان: چند جوان تحصیل‌کرده در حوزه‌ی علوم انسانی تصمیم گرفته‌اند مستقل باشند چراکه خیال می‌کنند، استقلال مالی مقدمه‌ی استقلال فکری است. در ادامه تلاش می‌کنند برای رسیدن به هدفشان شاغل شوند اما ...    ",
//   },
//   {
//     section: "تئاتر",
//     name: "سوسمار",
//     director: "رحمت امینی",
//     genre: "تئاتر",
//     time: "۶۰",
//     description:
//       "نمایش سوسمار به کارگردانی رحمت امینی و نویسندگی حمید جبلی است که از ۶ شهریور تا ۶ مهر در سالن چارسوی تئاتر شهر اجرا می‌شود. بهار مشیری، ابوذر ساعدی، فرزاد برهمن، عرفان معصومی و نوید جهانزاده بازیگران سوسمار هستند.",
// synopsis :" خلاصه داستان: دقایقی مانده به سال تحویل، زن و مردی که در حال آماده سازی سفره هفت‌سین و آغاز سال تازه هستند، تخم‌مرغی برای رنگ کردن تهیه می‌کنند؛ ساعاتی بعد، تخم‌مرغ ترک می‌خورد و….    ",
//   },
//   {
//     section: "تئاتر",
//     name: "اتول سورون طهران الف ۱",
//     director: "شهروز دل افکار",
//     genre: "تئاتر",
//     time: "۸۰",
//     description:
//       "نمایش اتول سورون طهران الف ۱ به کارگردانی و تهیه‌کنندگی شهروز دل‌افکار و نویسندگی باقر سروش است که از ۷ شهریور تا ۲ مهر در پردیس تئاتر شهرزاد اجرا می‌شود. شهروز دل‌افکار، سحر عبدالملکی، رضا جهانگیری، محمدحسین معتمدی، هومان زمانی، فرحان شجاعی، محمدحسین بیات، عرشیا چاکرالحسینی، علیرضا خراسانی و ماهان زارعی برخی از بازیگران این نمایش را شامل می‌شوند.    ",
//   },
//   {
//     section: "تئاتر",
//     name: "کابوس‌های شازده اجباری",
//     director: "افشین زمانی",
//     genre: "تئاتر",
//     rate: "۴.۰",
//     view: "۱",
//     time: "۷۰",
//     description:
//       "نمایش کابوس‌های شازده اجباری به کارگردانی و نویسندگی افشین زمانی است که از 2 تا 31 شهریور در پردیس تئاتر شهرزاد اجرا می‌شود.پیمان محمدی، محمد سعادت، مبینا سلیمان‌فلاح، امیرحسین نعیمی، نجمه نصیری، مهسا ظهیری و ... بازیگران این نمایش را شامل می‌شوند.",
// synopsis :" خلاصه داستان: شازده خسرو خسته و خمیده، به خانه بازمی‌گردد و با جنازه‌ی خود روبرو می‌شود.    ",
//     actorName1: "پیمان محمدی",
//     actorName2: "محمد سعادت",
//     actorName3: "مبینا سلیمان فلاح",
//   },
//   {
//     section: "تئاتر",
//     name: "زیرزمینی‌ها",
//     director: "حامد وکیلی",
//     genre: "تئاتر",
//     rate: "۴.۲",
//     view: "۲۲",
//     time: "۷۰",
//     description:
//       "نمایش زیرزمینی‌ها به کارگردانی حامد وکیلی، نویسندگی مرتضی شاه‌کرم و تهیه‌کنندگی احمد خوشرو است که از 8 تا 30 مهر در پردیس تئاتر شهرزاد اجرا می‌شود. مرضیه صدرایی، سیروس همتی، حامد وکیلی، حنیف مظفری، شیوا جوانمرد، هانیه کریمی و آرمیتا لطفی بازیگران این نمایش هستند.    ",
//   },
//   {
//     section: "هنر و تجربه",
//     name: "مقیمان ناکجا",
//     director: "شهاب حسینی",
//     genre: "داستانی",
//     rate: "۴.۴",
//     view: "۹۷",
//     time: "۱۵۰",
//     description:
//       "فیلم مقیمان ناکجا به کارگردانی شهاب حسینی و محصول سال 1396 است. پریناز ایزدیار، آرمان درویش، ناهید مسلمی، احمد ساعتچیان، غزاله نظر، مهدی حسینی، تنی آواکیان و شهاب حسینی بازیگران این فیلم را شامل می‌شوند. عوامل مقیمان ناکجا عبارت‌اند از: مدیر فیلمبرداری: علی قاضی، تدوین: شهاب حسینی، شهرام ابراهیمی، مدیر تولید: شهرام زاهدی، طراح صحنه: پیام اسکندری و شهاب حسینی، طراح گریم: سیدجلال موسوی، طراح لباس: ژاله زکی‌زاده، صدابردار: محمد مختاری، صداگذار: حسین قورچیان، برنامه‌ریز: علیرضا نسایی، دستیار کارگردان: حسین ایرجی، منشی صحنه: روح‌ انگیز شمس، مدیر صحنه: رضا حسن‌وند، عکاس: نوشین جعفری، جلوه‌های ویژه: آرش آقابیگ. خلاصه فیلم: جوانی مرفه اما دل‌زده از زندگی، شبی در راه بازگشت به خانه، سر از مکانی غریب و بیگانه در می‌آورد. او به مرور و پس از آشنایی با مقیمان آن جا به واقعیت آن مکان پی برده و به حقایقی عمیق آگاه می‌شود.    ",
//     actorName1: "پریناز ایزدیاز",
//     actorName2: "آرمان درویش",
//     actorName3: "ناهید مسلمی",
//   },
//   {
//     section: "هنر و تجربه",
//     name: "کاپیتان من",
//     director: "سیاوش صفاریان پور",
//     genre: "مستند",
//     rate: "۴.۳",
//     view: "۳۱",
//     time: "۷۰",
//     description:
//       "فیلم کاپیتان من به کارگردانی سیاوش صفاریان‌پور و تهیه‌کنندگی بهرام رادان در ژانر مستند ساخته شده است.",
// synopsis :" خلاصه داستان: در این مستند سینمایی بهرام رادان به عنوان راوی به مغز انسان سفر می‌کند و به تحقیق درباره عملکرد آن می‌پردازد.    ",
//   },
//   {
//     section: "هنر و تجربه",
//     name: "هایپاور",
//     director: "هادی محمد پور",
//     genre: "جنگي | دفاع مقدس",
//     time: "۸۰",
//     description:
//       "فیلم هایپاور به کارگردانی هادی محمدپور و تهیه‌کنندگی امیر جوکار و مهدی عظیمی‌میرآبادی است. اتابک نادری، فرزاد حسنی، علیرام نورایی، سپیده خداوردی، مهرداد ضیایی، مجید پتکی، الناز اسماعیلی، رضوان خدامی، آرمان جوکار و هادی محمدپور بازیگران این فیلم هستند.",
// synopsis :" خلاصه داستان: هایپاور داستان نقش پدافند هوایی ارتش در عملیات والفجر هشت و طرح ابتکاری شهید منصور ستاری است    ",
//   },
//   {
//     section: "تئاتر کمدی",
//   },

//   {
//     section: "فیلم خارجی",
//   },
// ];

export const Movie = [
  {
    id: 100,
    section: "فیلم ایرانی",
    name: "هتل",
    director: "سید مسعود اطیابی",
    genre: "کمدی",
    rate: "۴.۳",
    view: "۶۳",
    time: "110",
    yearOfMade: 1402,
    amount: "19,382,500,500",
    description:
      "فیلم هتل به کارگردانی مسعود اطیابی و تهیه‌کنندگی محمد شایسته با بازی پژمان جمشیدی، محسن کیایی است. ریما رامین‌فر، صدف اسپهبدی، مهلقا باقری، غلامرضا نیکخواه، مریم وحیدزاده، فرزانه قاسم‌زاده، جواد پولادی و سام نوری نیز سایر بازیگران هتل هستند.",
    synopsis: " خلاصه داستان: کی بهشت رو ول می‌کنه بره جهنم؟!",
    actors: [
      "پژمان جمشیدی",
      "محسن کیایی",
      "صدف اسپهبدی",
      "ریما رامین فر",
      "مه‌لقا باقری",
      "غلامرضا نیکخواه",
      "مریم وحیدزاده",
      "فرزانه قاسم زاده",
      "جواد پولادی",
      "سام نوری",
    ],
    actorName1: "پژمان جمشیدی",
    actorName2: "محسن کیایی",
    actorName3: "صدف اسپهبدی",
    actorName4: "ریما رامین فر",
    actorName5: "مه‌لقا باقری",
    actorName6: "غلامرضا نیکخواه",
    actorName7: "مریم وحیدزاده",
    actorName8: "فرزانه قاسم زاده",
    actorName9: "جواد پولادی",
    actorName10: "سام نوری",
  },
  {
    section: "فیلم ایرانی",
    name: "بچه زرنگ",
    genre: "ماجراجویی | کودک و نوجوان",
    rate: "۴.۷",
    view: "۲۰",
    time: "۸۵",
    amount: "10,310,468,422",
    description:
      "انیمیشن بچه زرنگ ساخته گروه هنرپویا درباره‌ ماجرای پسر بچه‌ای به نام محسن است که خود را ابرقهرمان می‌داند و در یک اتفاق نادر، به جنگلی اسرار آمیز قدم می‌گذارد و با حیوانات منقرض شده ایران مواجه می‌شود… این آغاز یک ماجرای پیچیده برای نجات آخرین ببر ایرانی. فیلم انیمیشنی بچه زرنگ ساخته گروه هنرپویا گروه هنر پویا به تهیه‌کنندگی حامد جعفری است. صداپیشگان این فیلم عبارت‌اند از: سعید شیخ‌زاده، هومن حاجی‌عبداللهی، هدایت هاشمی، میرطاهر مظلومی، ژرژ پطروسی، جواد پزشکیان، مینا قیاس‌پور، مریم رادپور، تورج نصر، اردشیر منظم، مهسا عرفانی، ابراهیم شفیعی، همت مومی‌وند، .شایان شامبیاتی، حسن کاخی، امیر حکیمی، نازنین یاری، علیرضا دیباج، متانت اسماعیلی، پویا فهیمی.    ",
    actors: [
      "هومن حاجی عبداللهی",
      "سعید شیخ زاده",
      "هدایت هاشمی",
      "میرطاهر مظلومی",
      "ژرژ پطروسی",
    ],
    actorName1: "هومن حاجی عبداللهی",
    actorName2: "سعید شیخ زاده",
    actorName3: "هدایت هاشمی",
    actorName4: "میرطاهر مظلومی",
    actorName5: "ژرژ پطروسی",
    id: 101,
  },
  {
    section: "فیلم ایرانی",
    name: "بی مادر",
    director: "سید مرتضی فاطمی",
    genre: "اجتماعی",
    rate: "۳.۶",
    view: "۴۱۴",
    time: "۸۵",
    amount: "9,546,462,010",
    description:
      "فیلم بی مادر به کارگردانی سیدمرتضی فاطمی و تهیه‌کنندگی محمدرضا مصباح و علی اوجی در ژانر اجتماعی ساخته شده است. بی مادر با حضور در چندین جشنواره معتبر بین‌المللی از جمله جشنواره بین‌المللی فیلم داکا، جشنواره‌‌ بین‌المللی‌ بنگلور، جشنواره کراسینگ اسکرین و جشنواره رینبو لندن، موفق به کسب جوایز متعددی شده است. در این فیلم بازیگرانی همچون امیر آقایی، پژمان جمشیدی، میتراحجار به ایفای نقش پرداخته‌اند. برخی از عوامل فیلم عبارت‌اند از: مدیر فیلمبرداری: مسعود سلامی، چهره‌پرداز: محمود دهقانی، طراح صحنه: سهیل دانش اشراقی، تدوین:‌ محمد نجاریان، بهرام دهقانی، صدابردار: بابک اردلان.",
    synopsis:
      " خلاصه داستان: زندگی آرام یک زوج با پافشاری یکی از آنها روی تصمیمش، ناخواسته وارد دو راهی‌ها و مخاطرات اخلاقی پیچیده‌ای می‌شود.",
    actorName1: "امیر آقایی",
    actorName2: "پژمان جمشیدی",
    actorName3: "میترا حجاز",
    actorName4: "پردیس پورعابدینی",
    actorName5: "علی اوجی",
    actorName6: "سارا محمدی",
    actorName7: "بیتا عزیزاوقلو",
    id: 102,
  },
  {
    section: "فیلم ایرانی",
    name: "نارگیل ۲",
    director: "داود اطیابی",
    genre: "کمدی",
    rate: "۳.۶",
    view: "۱۳۳",
    time: "۸۰",
    amount: "11,112,523,100",
    description:
      "فیلم نارگیل 2 به کارگردانی سیدداود اطیابی و تهیه‌کنندگی سیدابراهیم عامریان است که ژانری کمدی دارد. بیژن بنفشه‌خواه، علیرضا استادی، سحر قریشی، شقایق دهقان، نصرالله رادش و غلامحسین لطفی بازیگران اصلی این فیلم هستند.",
    actorName1: "غلامحسین لطفی",
    actorName2: "بیژن بنفشه خواه",
    actorName3: "علیرضا استادی",
    actorName4: "سحر قریشی",
    actorName5: "شقایق دهقان",
    actorName6: "نصرالله رادش",
    actorName7: "امید روحانی",
    actorName8: "مانیا علیجانی",
    actorName9: "آرین اسماعیلی",
    id: 103,
  },
  {
    section: "فیلم ایرانی",
    name: "بعد از رفتن",
    director: "رضا نجاتی",
    genre: "درام",
    rate: "۲.۸",
    view: "۶۱",
    amount: "19,681,419,000",
    description:
      "فیلم بعد از رفتن به کارگردانی رضا نجاتی و تهیه‌کنندگی محمود بابایی است. صابر ابر، سارا بهرامی، پوریا رحیمی‌سام، پانته‌آ پناهی‌ها، بهرام شاه‌محمدلو، احترام برومند و ... بازیگران این فیلم هستند.",
    synopsis:
      " خلاصه داستان: آرش بعد از مدت‌ها دوری به زادگاهش باز می‌گردد و به دنبال گمشده‌اش است…    ",
    actorName1: "صابر ابر",
    actorName2: "سارا بهرامی",
    actorName3: "پوریا رحیمی سام",
    actorName4: "پانته آ پناهی‌ها",
    actorName5: "بهرام شاه محمدلو",
    actorName6: "احترام برومند",
    actorName7: "روشنک گرامی",
    actorName8: "یسنا میرطهماسب",
    actorName9: "خسرو احمدی",
    actorName10: "حامی ترابی",
    id: 104,
  },
  {
    section: "فیلم ایرانی",
    name: "شهر هرت",
    director: "کریم امینی",
    genre: "کمدی",
    rate: "۲.۹",
    view: "۸۰۴",
    time: "۹۵",
    amount: "65,254,900,125",
    description:
      "فیلم شهر هرت به کارگردانی کریم امینی و تهیه‌کنندگی محمدحسین فرح‌بخش است و ژانری کمدی دارد. پژمان جمشیدی، شبنم مقدمی و بابک کریمی بازیگران اصلی این فیلم را شامل می‌شوند.    ",
    actorName1: "پژمان جمشیدی",
    actorName2: "شبنم مقدمی",
    actorName3: "بابک کریمی",
    actorName4: "اکبر رحمتی",
    id: 105,
  },
  {
    section: "فیلم ایرانی",
    name: "هولیا",
    director: "مرتضی آتش زمزم",
    genre: "کمدی",
    rate: "۲.۹",
    view: "۱۴۲",
    amount: "5,676,878,320",
    description:
      "فیلم کمدی موزیکال هولیا به کارگردانی مرتضی آتش‌زمزم است که در آن بازیگرانی همچون پوریا پورسرخ، محمد رضا هدایتی، علی انصاریان، مریم امیرجلالی و بهراد خرازی ایفای نقش کرده‌اند.    ",
    actorName1: "پوریا پورسرخ",
    actorName2: "محمدرضا هدایتی",
    actorName3: "علی انصاریان",
    actorName4: "مریم امیرجلالی",
    actorName5: "بهراد خرازی",
    actorName6: "محمد فیلی",
    actorName7: "افشین سنگ چاپ",
    actorName8: "مجید شهریاری",
    actorName9: "شراره رخام",
    actorName10: "شیوا خسرومهر",
    actorName11: "شیوا طاهری",
    actorName12: "مهدی امینی خواه",
    actorName13: "مهدی امینی",
    actorName14: "علی کوچولو",
    actorName15: "مهدی حسینی",
    actorName16: "مریم نقیب",
    actorName17: "هدی استواری",
    actorName18: "شیما جوهری",
    actorName19: "مسعود حقی",
    id: 106,
  },
  {
    section: "فیلم ایرانی",
    name: "فسیل",
    director: "کریم امینی",
    genre: "کمدی",
    rate: "۴.۵",
    view: "۳۷۰۵",
    amount: "263,657,031,014",
    description:
      "فیلم فسیل به کارگردانی کریم امینی و تهیه‌کنندگی ابراهیم عامریان است. بهرام افشاری، هادی کاظمی، الناز حبیبی، الهه حصاری، ایمان صفا، بابک کریمی، سیدجواد هاشمی و ... در این فیلم کمدی ایفای نقش کرده‌اند. خلاصه فیلم: با فسيل به دهه پنجاه سفر كنيد...    ",
    actorName1: "بهرام افشاری",
    actorName2: "هادی کاظمی",
    actorName3: "الناز حبیبی",
    actorName4: "الهه حصاری",
    actorName5: "ایمان صفا",
    actorName6: "بابک کریمی",
    actorName7: "سید جواد هاشمی",
    actorName8: "غلامرضا نیکخواه",
    actorName9: "سمانه منیری",
    actorName10: "امید روحانی",
    actorName11: "علیرضا استادی",
    actorName12: "قاسم زارع",
    actorName13: "خشایار راد",
    actorName14: "مجید شهریاری",
    id: 107,
  },
  {
    section: "فیلم ایرانی",
    name: "زنبور کارگر",
    director: "افشین صادقی",
    genre: "اجتماعی",
    rate: "۳.۳",
    view: "۴۷",
    amount: "4,532,879,012",
    description:
      "فیلم زنبور کارگر به کارگردانی و تهیه‌کنندگی افشین صادقی و نویسندگی سعید نعمت‌الله است. حمید فرخ‌نژاد، شبنم مقدمی، سعید آقاخانی، پگاه آهنگرانی، حسن مهری و ... بازیگران این فیلم را شامل می‌شوند.    ",
    id: 108,
  },
  {
    section: "فیلم ایرانی",
    name: "آخرین تولد",
    director: "نوید محمودی",
    genre: "درام",
    rate: "۲.۷",
    view: "۱۷۳",
    time: "۸۵",
    amount: "8,666,020,158",
    description:
      "فیلم آخرین تولد به کارگردانی و نویسندگی نوید محمودی و تهیه‌کنندگی جمشید محمودی است. الناز شاکردوست، پدرام شریفی، شیدا خلیق، آرمین رحیمیان، سوگل خلیق، نیلوفر کوخانی و رضا بهبودی بازیگران این فیلم را شامل می‌شوند.",
    synopsis:
      " خلاصه داستان: روایتی از عشق ثریا و فهیم؛ عشقی که سایه‌ جنگ بر سرش آوار شده است، غزلی است عاشقانه در دل بحران...    ",
    actorName1: "الناز شاکردوست",
    actorName2: "پدرام شریفی",
    actorName3: "شیدا خلیق",
    actorName4: "آرمین رحیمیان",
    actorName5: "سوگل خلیق",
    actorName6: "نیلوفر کوخانی",
    actorName7: "رضا بهبودی",
    id: 109,
  },
  {
    section: "فیلم ایرانی",
    name: "شماره ۱۰",
    director: "حمید زرگرنژاد",
    genre: "دفاع مقدس",
    rate: "۴.۰",
    view: "۳۳",
    amount: "10,022,156,008",
    description:
      "فیلم شماره 10 به نویسندگی و کارگردانی حمید زرگرنژاد و تهیه‌کنندگی ابراهیم اصغری است. در این فیلم بازیگرانی همچون مجید صالحی، حسام منظور، سیامک صفری و صحرا اسداللهی ایفای نقش می‌کنند.",
    synopsis:
      " خلاصه داستان: فرار از اینجا بهترین راهه چون همه‌مون ازش می‌ترسیم…    ",
    actorName1: "مجید صالحی",
    actorName2: "حسام منظور",
    actorName3: "سیامک صفری",
    actorName4: "مهدی زمین پرداز",
    actorName5: "بهرنگ علوی",
    actorName6: "صحرا اسداللهی",
    actorName7: "احمد کاوری",
    id: 110,
  },
  {
    section: "فیلم ایرانی",
    name: "ستاره بازی",
    director: "هاتف علیمردانی",
    genre: "اجتماعی",
    rate: "۳.۳",
    view: "۱۸۱",
    amount: "3,649,284,165",
    description:
      "فیلم ستاره بازی به کارگردانی و نویسندگی هاتف علیمردانی و تهیه‌کنندگی علی سرتیپی است. در این فیلم بازیگرانی چون فرهاد اصلانی، شبنم مقدمی، ملیسا ذاکری، علی مصفا و مایکل مدسن ستاره سینمای آمریکا به همراه مارشال منش، لیندا جویز، هاوارد رسنزتین و دان لیستر ایفای نقش کرده‌اند.",
    synopsis:
      " خلاصه داستان: امروز بیست‌و‌نه نوامبره، از اون هالووین لعنتی یه ماه می‌گذره، من یه کار بد کردم، یه کار خیلی بد...    ",
    actorName1: "فرهاد اصلانی",
    actorName2: "شبنم مقدمی",
    actorName3: "ملیسا ذاکری",
    actorName4: "علی مصفا",
    actorName5: "مایکل مدسن",
    actorName6: "مارشال منش",
    actorName7: "لیندا جویز",
    actorName8: "هاوارد رسنزتین",
    actorName9: "دان لیستر",
    id: 111,
  },
  {
    section: "فیلم ایرانی",
    name: "ستون ۱۴",
    director: "امیرحسین همتی",
    genre: "اجتماعی",
    rate: "۳.۴",
    view: "۲۰۲",
    time: "۹۵",
    amount: "1,645,899,423",
    description:
      "ستون 14 به کارگردانی و نویسندگی امیرحسین همتی است که در آن بازیگرانی همچون میترا حجار، روزبه حصاری، میلاد رحیمی، مهسا باقری و علی میلانی ایفای نقش می‌کنند. این فیلم توسط علیرضا قاسم‌خان تهیه‌کنندگی شده است. دیگر عوامل ستون 14 عبارت‌اند از: فیلمبردار: مسعود امینی تیرانی، مجری طرح و مدیر تولید: سید احمد ساکت، مشاور کارگردان: احمد امینی، طراحی و ترکیب صدا: ندا محسنی، تدوین: پرهام وفایی، صدابردار: شهرام متولی‌باشی، موسیقی: مهدی محمود‌خانی، طراح گریم: الهام صالحی، طراح صحنه: امیرحسین همتی.",
    synopsis:
      " خلاصه داستان: ساناز و یاشار وقتی می‌ترسند، بازی می‌کنند. این‌بار با زندگی جلال …    ",
    actorName1: "میترا حجاز",
    actorName2: "روزبه حصاری",
    actorName3: "میلاد رحیمی",
    actorName4: "مهسا باقری",
    actorName5: "علی میلانی",
    id: 112,
  },
  {
    section: "فیلم ایرانی",
    name: "دست انداز",
    director: "کمال تبریزی",
    genre: "درام",
    rate: "۳.۱",
    view: "۱۲۷",
    time: "۸۴",
    amount: "2,654,852,111",
    description:
      "فیلم دست انداز به کارگردانی کمال تبریزی، نویسندگی فرزاد فخری‌زاده و تهیه‌کنندگی محمد آفریده است. امید نعمتی، هدی زین‌العابدین، رویا نونهالی رضا کیانیان بازیگران اصلی این فیلم را شامل می‌شوند.",
    synopsis:
      " خلاصه داستان: رها که علاقه‌مند به نویسندگی است آخرین داستان خود را با آرزوهایش همراه می‌کند.    ",
    actorName1: "رضا کیانیان",
    actorName2: "امید نعمتی",
    actorName3: "هدی زین العابدین",
    actorName4: "حبیب رضایی",
    actorName5: "همایون ارشادی",
    actorName6: "رویا نونهالی",
    actorName7: "محمدرضا حسین زاده",
    id: 113,
  },
  {
    section: "فیلم ایرانی",
    name: "کت چرمی",
    director: "حسین میرزامحمدی",
    genre: "درام | معمایی",
    rate: "۳.۲",
    view: "۵۱۸",
    amount: "14,422,684,250",
    description:
      "فیلم کت چرمی به کارگردانی حسین میرزامحمدی، نویسندگی مسعود هاشمی‌نژاد و محصول سال 1401 است. جواد عزتی، صابر ابر، گلاره عباسی، پانته‌آ پناهی‌ها و ستاره پسیانی بازیگران اصلی این فیلم هستند. برخی از عوامل کت چرمی عبارت‌اند از: مجری طرح: پیمان حجازی، مدیر فیلمبرداری: آرمان فیاض، تدوین: عماد خدابخش، آهنگساز: مسعود سخاوت دوست، مدیرتولید: پیمان حمیدی، مدیر صدابرداری: محمد شاهوردی، طراحی و ترکیب صدا: آرش قاسمی، طراح صحنه: بهزاد جعفری طادی. خلاصه فیلم: عیسی فرهمند، کارمند بازرسی سازمان بهزیستی در جریان بازدید از یک مرکز نگهداری دختران خیابانی، متوجه باند فساد مشکوکی می‌شود که او را به یک مهمانی زیرزمینی ممنوعه می‌رساند‌؛ مهمانی کُت‌چرمی ...    ",
    actorName1: "جواد عزتی",
    actorName2: "صابر ابر",
    actorName3: "گلاره عباسی",
    actorName4: "پانته آ پناهی ها",
    actorName5: "ستاره پسیانی",
    actorName6: "عباس جمشیدی‌فر",
    actorName7: "مائده طهماسبی",
    actorName8: "بهزاد خلج",
    actorName9: "امین میری",
    actorName10: "محمد صدیقی مهر",
    actorName11: "آیدا ماهیانی",
    actorName12: "سارا حاتمی",
    actorName13: "رویا تیموریان",
    actorName14: "سیامک احصایی",
    id: 114,
  },
  {
    section: "کودک و نوجوان",
    name: "لب خنده",
    director: "آرش ابراهیم زاده",
    genre: "کودک",
    rate: "۵",
    view: "۱۳",
    description:
      "نمایش لب خنده به نویسندگی و کارگردانی آرش ابراهیم‌زاده است که از 20 تیر تا 20 مهر در پردیس سینمایی هدیش‌مال اجرا می‌شود. محمد سروش‌فر، جواد سلیمانی، رامبد پورمفخمی، ملیکا حسینی، کیانا تعصبی و ... بازیگران این نمایش هستند. خلاصه نمایش: حسینقلی پسری که با سفر پدرش دلتنگ شده بود و مدام گریه می‌کرد و نمی‌خندید، برای به دست آوردن لب خنده‌اش سفری خیالی را شروع می‌کند تا بتواند به شادی و خنده حقیقی برسد...    ",
    id: 115,
  },
  {
    section: "کودک و نوجوان",
    name: "فیلم انیمیشن لوکا (Luca)",
    director: "انریکو کاساروسا",
    genre: "کودک و نوجوان | دوبله",
    rate: "۴.۶",
    view: "۳۴",
    time: "۹۶",
    description:
      "انیمیشن لوکا یک انیمیشن تخیلی محصول شرکت انیمیشن سازی پیکسار است. کارگردانی این فیلم بر عهده انریکو کاساروسا بوده است و در این فیلم جیکوب ترمبلی، جک دیلان گریزر، اما برمن، ساوریو رایموندو، مایا رودولف، مارکو باریکلی و جیم گفین صداپیشگی می‌کنند. این فیلم در سال 2021 ساخته و اکران شد و مدت زمان این فیلم 95 دقیقه است. خلاصه فیلم: در ریوریای ایتالیا، یک دوستی عجیب و قوی بین یک انسان و یک غول دریایی که انسان‌ها فراری است شکل می‌گیرد.    ",
    id: 116,
  },
  {
    section: "کودک و نوجوان",
    name: "بابا سیبیلو",
    director: "ادوین خاچیکیان",
    genre: "کودک",
    rate: "۲.۶",
    view: "۴۴",
    description:
      "فیلم بابا سیبیلو به کارگردانی ادوین خاچیکیان و تهیه‌کنندگی احمد احمدی است. این فیلم ژانری کمدی-خانوادگی دارد و بازیگرانی همچون رضا شفیعی‌جم، بهاره رهنما، امیرحسین صدیق و عباس محبوب در آن ایفای نقش کرده‌اند.    ",
    id: 117,
  },
  {
    section: "کودک و نوجوان",
    name: "آرزوی الاغ",
    director: "محمدحسین داداش نیا",
    genre: "کودک و نوجوان",
    rate: "۵",
    view: "۱",
    time: "۵۵",
    description:
      "نمایش آرزوی الاغ به کارگردانی و نویسندگی محمدحسین داداش‌نیاست که از 3 مهر تا 3 آبان در فرهنگسرای فردوس اجرا می‌شود. محمدحسین داداش‌نیا، نرگس نیک‌سیرت، مریم اسکندری، بهاره رمه‌چی و پروا نریمانی بازیگران این نمایش هستند.",
    synopsis:
      " خلاصه داستان: الاغ آرزو می‌کند تا مثل یک پروانه باشد ولی بر اساس ماجرایی متوجه می‌شود که باید به الاغ بودنش افتخار کند.    ",
    id: 118,
  },
  {
    section: "کودک و نوجوان",
    name: "نیم وجبی",
    director: "علیرضا دهقانی",
    genre: "کودک و نوجوان",
    rate: "۲.۵",
    view: "۴",
    time: "۵۰",
    description:
      "نمایش نیم وجبی از 10 تا 31 مرداد در فرهنگسرای فردوس اجرا می‌شود.    ",
    id: 119,
  },
  {
    section: "کودک و نوجوان",
    name: "خاله‌سوسکه",
    genre: "کودک و نوجوان",
    rate: "۲.۷",
    description:
      "نمایش خاله سوسکه به نویسندگی و کارگردانی مهرداد قرآن‌کیش است که در فرهنگسرای ابن‌سینا اجرا می‌شود.    ",
    id: 120,
  },
  {
    section: "کودک و نوجوان",
    name: "بل و شاهزاده‌ مغرور",
    director: "علیرضا دهقانی",
    genre: "کودک و نوجوان",
    rate: "۵",
    view: "۳",
    time: "۵۰",
    description:
      "نمایش بل و شاهزاده مغرور به کارگردانی علیرضا دهقانی و نویسندگی ماندانا عبقری است که از 28 شهریور تا 28 مهر در پردیس تئاتر شهرزاد می‌شود. ماندانا عبقری، دیار باغی، محمدرضا لطفی، هادی شبانی، لیلا احمدی و بهار حسین زادگان در این نمایش نقش‌آفرینی کرده‌اند.",
    synopsis:
      " خلاصه داستان: در قصری زیبا شاهزاده‌ای مغرور و بدخلق زندگی می‌کند، شبی طوفانی جادوگری به قصر پناه می‌برد اما شاهزاده او را به قصر راه نمی‌دهد. جادوگر شاهزاده و خدمتکارانش را جادو می‌کند، شاهزاده به موجودی عجیب تبدیل می‌شود.    ",
    id: 121,
  },
  {
    section: "تئاتر",
    name: "اسکرین شات",
    director: "امیر عباسی",
    genre: "تئاتر",
    rate: "۴.۵",
    view: "۱۰",
    time: "۶۰",
    description:
      "اسکرین شات به کارگردانی امیر عباسی و نویسندگی و تهیه‌کنندگی سامان شمس است که از 28 تیر تا 27 مرداد در پردیس تئاتر شهرزاد (سالن سه) اجرا می‌شود. امیرحسین رضازاده، حامد آرامی، امیرحسین همایونی، ستاره فلاح‌فرد، سحر قلباروند، حسین جاهد، رومینا کوهزاد و مرضیه ابراهیمی بازیگران این نمایش هستند.",
    synopsis:
      " خلاصه داستان: فرض کنید در یک دورهمی در کنار همسر و دوستانتان، مجبور شوید تمام محتویات تلفن همراهتان را با صدای بلند بخوانید.    ",
    id: 122,
  },
  {
    section: "تئاتر",
    name: "سه شب با مادوکس",
    director: "شیوا دیناروند",
    genre: "تئاتر",
    rate: "۵",
    view: "۱",
    time: "۶۰",
    description:
      "نمایش سه شب با مادوکس به کارگردانی شیوا دیناروند و تهیه‌کنندگی او با مجید یارندی پور است که از 29 شهریور تا 25 مهر در تالار حافظ اجرا می‌شود. مسعود کرامتی، بهاره رهنما، سیدجواد یحیوی، وحید نفر و میلاد رمضانی بازیگران این نمایش هستند.",
    synopsis:
      " خلاصه داستان: شخص مرموزی به نام مادوکس در شهری حاضر شده و ساکنان شهر به وحشت افتاده‌اند.    ",
    id: 123,
  },
  {
    section: "تئاتر",
    name: "پدر",
    director: "آروند دشت آرای",
    genre: "تئاتر",
    time: "۸۰",
    description:
      "نمایش پدر به کارگردانی آروند دشت آرای و تهیه‌‎کنندگی محمد قدس است که از 17 مهر تا 26 آبان در سالن اصلی تئاتر شهر اجرا می‌شود. رضا کیانیان، مارین ون هولک، سعید چنگیزیان، سوگل خلیق، بهزاد کریمی و پریسا شاه‌ولیان بازیگران این نمایش هستند.",
    synopsis:
      " خلاصه داستان: «پدر» تجربه‌ای دردناک و بکری است از زوال عقل (آلزایمر)، که به وضعیت او و ارتباط با دخترش می‌پردازد.    ",
    id: 124,
  },
  {
    section: "تئاتر",
    name: "کانال",
    director: "مرتضی فروزان فر",
    genre: "تئاتر",
    rate: "۱.۰",
    view: "۱",
    time: "۷۰",
    description:
      "نمایش کانال به نویسندگی و کارگردانی مرتضی فروزان‌فر و تهیه‌کنندگی مطهره عباسی است که از 5 تا 25 مهر در عمارت ارغوان اجرا می‌شود. شهرزاد بیانی، لیلا شاهی، محمدجواد عارف‌اصیل، سجاد حیدریه، علیرضا اتابکی، امیرحسین شیشه‌گران، حامد لطفی، امید محمدی، حمید صالحی و مرتضی فروزان‌فر بازیگران این نمایش هستند.",
    synopsis: " خلاصه داستان: جهان تک‌صدایی‌ست در رفت‌وآمد که..    ",
    id: 125,
  },
  {
    section: "تئاتر",
    name: "کمدی گمنام",
    director: "علی اصغری",
    genre: "تئاتر",
    time: "۶۰",
    description:
      "نمایش کمدی گمنام به کارگردانی و نویسندگی علی اصغری است که از 6 مهر تا 9 آبان در عمارت نوفل‌لوشاتو اجرا می‌شود. فرزاد حسنی و حسین پورکریمی بازیگران اصلی این نمایش هستند.",
    synopsis:
      " خلاصه داستان: دو دوست قدیمی و هنرور سینما در سال‌های پس از انقلاب ۱۳۵۷ گمان می‌کنند که ممنوع‌الکار شده‌اند و بدین سبب دست به هر کاری می‌زنند.    ",
    id: 126,
  },
  {
    section: "تئاتر",
    name: "طبیب اجباری",
    director: "سهیل جمشیدی",
    genre: "تئاتر",
    time: "۷۵",
    description:
      "نمایش طبیب اجباری به کارگردانی سهیل جمشیدی و تهیه‌کنندگی هاتف کلاته است که از 6 تا ۲۰ مهر در خانه نمایش دا اجرا می‌شود. افشین قدیمی، نازنین‌زهرا مقدسی، مریم حاج‌محمدی، محمد مغانی، عباس ستارزاده، ‌مهشید زبردست، سهیل جمشیدی و ، پویا رفیعی‌نژاد بازیگران این نمایش هستند.    ",
    id: 127,
  },
  {
    section: "تئاتر",
    name: "بنگاه تئاترال",
    director: "هادی مرزبان",
    genre: "تئاتر",
    time: "۱۰۰",
    description:
      "نمایش بنگاه تئاترال به کارگردانی هادی مرزبان، نویسندگی علی نصیریان و تهیه‌کنندگی مسعود والاست که از 9 تا 30 مهر در سالن 1 پردیس تئاتر شهرزاد اجرا می‌شود. مجید مظفری، علی فتحعلی، رسول نجفیان، داوود فتحعلی‌بیگی، محمود بصیری، محمدهادی عطایی و ... بازیگران این نمایش هستند.    ",
    id: 128,
  },
  {
    section: "تئاتر",
    name: "جردن جنوبی",
    director: "شایان مستوفی",
    genre: "تئاتر",
    time: "۵۰",
    description:
      "نمایش جردن جنوبی به نویسندگی، کارگردانی و تهیه‌کنندگی شایان مستوفی است که از 3 مهرماه در پردیس تئاتر شهرزاد اجرا می‌شود. سپهر جاویدیان، ابوالفضل حضرتی، علیرضا محمدنژاد، اسحاق طاهری، نیما امامی، شایان مستوفی و رضا شفائی بازیگران این نمایش هستند.",
    synopsis: " خلاصه داستان: شبی که منو رفیقام با دایی تنها شدیم و ...    ",
    id: 129,
  },
  {
    section: "تئاتر",
    name: "عروس فراری",
    director: "جواد انصافی",
    genre: "تئاتر",
    time: "۷۰",
    description:
      "نمایش عروس فراری به نویسندگی و کارگردانی جواد انصافی، تهیه‌کنندگی مهرداد وکیلی است که از 3 تا 27 مهر در پردیس تئاتر شهرزاد اجرا می‌شود. جواد انصافی، امیر پارسی، امیرمحمد و امیرحسین انصافی، رضا معراجی، فرشته اعظمی و ... بازیگران این نمایش هستند.",
    synopsis:
      " خلاصه داستان: مادری در اثر فقر و نبود امنیت اقتصادی قصد دارد دخترش را به عقد پیرمردی دربیاورد. دختر با کمک عبدلی و یکی از همکلاسی‌های دانشگاهی‌اش نقشه‌ای می‌کشند.    ",
    id: 130,
  },
  {
    section: "تئاتر",
    name: "شقامک",
    director: "سلمان سامنی",
    genre: "تئاتر",
    time: "۶۰",
    description:
      "نمایش شقامک به نویسندگی و کارگردانی سلمان سامنی است که از 2 مهر تا 1 آبان در پردیس تئاتر شهرزاد اجرا می‌شود. مهدی رضایی، لیلی صبری، رسول احمدی، کامران طاهری و المیرا صارمی بازیگران این نمایش هستند.",
    synopsis:
      " خلاصه داستان: چند جوان تحصیل‌کرده در حوزه‌ی علوم انسانی تصمیم گرفته‌اند مستقل باشند چراکه خیال می‌کنند، استقلال مالی مقدمه‌ی استقلال فکری است. در ادامه تلاش می‌کنند برای رسیدن به هدفشان شاغل شوند اما ...    ",
    id: 131,
  },
  {
    section: "تئاتر",
    name: "سوسمار",
    director: "رحمت امینی",
    genre: "تئاتر",
    time: "۶۰",
    description:
      "نمایش سوسمار به کارگردانی رحمت امینی و نویسندگی حمید جبلی است که از ۶ شهریور تا ۶ مهر در سالن چارسوی تئاتر شهر اجرا می‌شود. بهار مشیری، ابوذر ساعدی، فرزاد برهمن، عرفان معصومی و نوید جهانزاده بازیگران سوسمار هستند.",
    synopsis:
      " خلاصه داستان: دقایقی مانده به سال تحویل، زن و مردی که در حال آماده سازی سفره هفت‌سین و آغاز سال تازه هستند، تخم‌مرغی برای رنگ کردن تهیه می‌کنند؛ ساعاتی بعد، تخم‌مرغ ترک می‌خورد و….    ",
    id: 132,
  },
  {
    section: "تئاتر",
    name: "اتول سورون طهران الف ۱",
    director: "شهروز دل افکار",
    genre: "تئاتر",
    time: "۸۰",
    description:
      "نمایش اتول سورون طهران الف ۱ به کارگردانی و تهیه‌کنندگی شهروز دل‌افکار و نویسندگی باقر سروش است که از ۷ شهریور تا ۲ مهر در پردیس تئاتر شهرزاد اجرا می‌شود. شهروز دل‌افکار، سحر عبدالملکی، رضا جهانگیری، محمدحسین معتمدی، هومان زمانی، فرحان شجاعی، محمدحسین بیات، عرشیا چاکرالحسینی، علیرضا خراسانی و ماهان زارعی برخی از بازیگران این نمایش را شامل می‌شوند.    ",
    id: 133,
  },
  {
    section: "تئاتر",
    name: "کابوس‌های شازده اجباری",
    director: "افشین زمانی",
    genre: "تئاتر",
    rate: "۴.۰",
    view: "۱",
    time: "۷۰",
    description:
      "نمایش کابوس‌های شازده اجباری به کارگردانی و نویسندگی افشین زمانی است که از 2 تا 31 شهریور در پردیس تئاتر شهرزاد اجرا می‌شود.پیمان محمدی، محمد سعادت، مبینا سلیمان‌فلاح، امیرحسین نعیمی، نجمه نصیری، مهسا ظهیری و ... بازیگران این نمایش را شامل می‌شوند.",
    synopsis:
      " خلاصه داستان: شازده خسرو خسته و خمیده، به خانه بازمی‌گردد و با جنازه‌ی خود روبرو می‌شود.    ",
    actorName1: "پیمان محمدی",
    actorName2: "محمد سعادت",
    actorName3: "مبینا سلیمان فلاح",
    id: 134,
  },
  {
    section: "تئاتر",
    name: "زیرزمینی‌ها",
    director: "حامد وکیلی",
    genre: "تئاتر",
    rate: "۴.۲",
    view: "۲۲",
    time: "۷۰",
    description:
      "نمایش زیرزمینی‌ها به کارگردانی حامد وکیلی، نویسندگی مرتضی شاه‌کرم و تهیه‌کنندگی احمد خوشرو است که از 8 تا 30 مهر در پردیس تئاتر شهرزاد اجرا می‌شود. مرضیه صدرایی، سیروس همتی، حامد وکیلی، حنیف مظفری، شیوا جوانمرد، هانیه کریمی و آرمیتا لطفی بازیگران این نمایش هستند.    ",
    id: 135,
  },
  {
    section: "هنر و تجربه",
    name: "مقیمان ناکجا",
    director: "شهاب حسینی",
    genre: "داستانی",
    rate: "۴.۴",
    view: "۹۷",
    time: "۱۵۰",
    description:
      "فیلم مقیمان ناکجا به کارگردانی شهاب حسینی و محصول سال 1396 است. پریناز ایزدیار، آرمان درویش، ناهید مسلمی، احمد ساعتچیان، غزاله نظر، مهدی حسینی، تنی آواکیان و شهاب حسینی بازیگران این فیلم را شامل می‌شوند. عوامل مقیمان ناکجا عبارت‌اند از: مدیر فیلمبرداری: علی قاضی، تدوین: شهاب حسینی، شهرام ابراهیمی، مدیر تولید: شهرام زاهدی، طراح صحنه: پیام اسکندری و شهاب حسینی، طراح گریم: سیدجلال موسوی، طراح لباس: ژاله زکی‌زاده، صدابردار: محمد مختاری، صداگذار: حسین قورچیان، برنامه‌ریز: علیرضا نسایی، دستیار کارگردان: حسین ایرجی، منشی صحنه: روح‌ انگیز شمس، مدیر صحنه: رضا حسن‌وند، عکاس: نوشین جعفری، جلوه‌های ویژه: آرش آقابیگ. خلاصه فیلم: جوانی مرفه اما دل‌زده از زندگی، شبی در راه بازگشت به خانه، سر از مکانی غریب و بیگانه در می‌آورد. او به مرور و پس از آشنایی با مقیمان آن جا به واقعیت آن مکان پی برده و به حقایقی عمیق آگاه می‌شود.    ",
    actorName1: "پریناز ایزدیاز",
    actorName2: "آرمان درویش",
    actorName3: "ناهید مسلمی",
    id: 136,
  },
  {
    section: "هنر و تجربه",
    name: "کاپیتان من",
    director: "سیاوش صفاریان پور",
    genre: "مستند",
    rate: "۴.۳",
    view: "۳۱",
    time: "۷۰",
    description:
      "فیلم کاپیتان من به کارگردانی سیاوش صفاریان‌پور و تهیه‌کنندگی بهرام رادان در ژانر مستند ساخته شده است.",
    synopsis:
      " خلاصه داستان: در این مستند سینمایی بهرام رادان به عنوان راوی به مغز انسان سفر می‌کند و به تحقیق درباره عملکرد آن می‌پردازد.    ",
    id: 137,
  },
  {
    section: "هنر و تجربه",
    name: "هایپاور",
    director: "هادی محمد پور",
    genre: "جنگي | دفاع مقدس",
    time: "۸۰",
    description:
      "فیلم هایپاور به کارگردانی هادی محمدپور و تهیه‌کنندگی امیر جوکار و مهدی عظیمی‌میرآبادی است. اتابک نادری، فرزاد حسنی، علیرام نورایی، سپیده خداوردی، مهرداد ضیایی، مجید پتکی، الناز اسماعیلی، رضوان خدامی، آرمان جوکار و هادی محمدپور بازیگران این فیلم هستند.",
    synopsis:
      " خلاصه داستان: هایپاور داستان نقش پدافند هوایی ارتش در عملیات والفجر هشت و طرح ابتکاری شهید منصور ستاری است    ",
    id: 138,
  },
  {
    section: "تئاتر کمدی",
    id: 139,
  },
  {
    section: "فیلم خارجی",
    id: 140,
  },
];
